### ISSUE TITLE
Links broken in the Readme.md

### ISSUE THREAD

**Issue by tmadhuker** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#1]
Hi, Team the links seem to be throwing the certificate error to me. Could you please check and correct them.??

https://azure.microsoft.com/en-us/regions/offers/ . 
https://azure.microsoft.com/en-us/global-infrastructure/services/

**Comment by polichtm** [comment]
These are official Microsoft web sites. 
How specifically would you want to "correct them"?
rgds
Marcin

**Comment by tmadhuker** [comment]
<img width="1440" alt="Screenshot 2019-05-04 at 3 37 32 PM" src="https://user-images.githubusercontent.com/20515288/57177575-a97f3200-6e82-11e9-885c-20b27a4bf57e.png">
<img width="1440" alt="Screenshot 2019-05-04 at 3 37 35 PM" src="https://user-images.githubusercontent.com/20515288/57177576-a97f3200-6e82-11e9-9b8f-be2de1bd56df.png">
Hi Polichtm,

Please find screenshots attached

**Comment by tiagocostapt** [comment]
@tmadhuker this is a problem on your end. Links are working just fine here.

![image](https://user-images.githubusercontent.com/11490197/57177858-54322900-6e60-11e9-90c4-07b7cc8997e9.png)

**Comment by tiagocostapt** [comment]
Can you check on another browser or clear local cache, etc...

**Comment by tmadhuker** [comment]
Hi @tiagocostapt, Thanks for the suggestion. There seems to be some issue with my ISP(Act Fibernet). I'm not sure how to fix this issue. I tried connecting to the site using the mobile network (Airtel 4G) and it is not showing the certificate error. Adding both the screenshots. is this the issue I need to bring into the notice of my ISP??
<img width="1440" alt="Screenshot 2019-05-04 at 3 37 32 PM" src="https://user-images.githubusercontent.com/20515288/57181236-b0bc3500-6eae-11e9-97d9-dd29d371691b.png">
<img width="1440" alt="Screenshot 2019-05-04 at 3 37 35 PM" src="https://user-images.githubusercontent.com/20515288/57181237-b154cb80-6eae-11e9-938c-fcd77bdd161f.png">

**Comment by tmadhuker** [comment]
Not sure what has happened but links seem to be working fine and are showing the proper certificate.
