### ISSUE TITLE
Labs 11b - Governance and Compliance (az-100-01b) Task 1: 6-9 

### ISSUE THREAD

**Issue by dmitry86** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#100]
Exercise 1: Tasks 6,9 can't be done in the order that the lab suggests. The new resource name is "Template deployment (deploy using custom templates) ". The parameters file _az-100-01b_azuredeploy.parameters.json_ won't load at all.

**Comment by polichtm** [comment]
Would you mind clarifying what you mean by "won't load at all"?
rgds
Marcin

**Comment by dmitry86** [comment]
Hi Marcin,
I couldn't upload the az-100-01b_azuredeploy.parameters.json file in the way the lab manual advised. You may try and see it will be denied.

**Comment by dpapkin** [comment]
Hi ,

Have you tried typing "cd" in the cloudshell to make sure you are in your home folder? Retry loading after that command

David Papkin

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dmitry86** [comment]
I'm not touching cloudshell as the lab doesn't suggest so. I'm doing as instructed via web interface. This is a brand new PAYG subscription. Simply trying to follow the lab script. I'll post a screenshot later.

**Comment by dmitry86** [comment]
OK, so I tried to reproduce just now. Basically you can't Load two templates as instructed. The first one should be saved first, to save a template you've to to enter the details from item 11. The lab order looks incorrect to me. 

Here's the screenshot https://prnt.sc/ovl9vf

**Comment by polichtm** [comment]
This is a parameters file - not a template. You are not supposed to load it as a template - but as a parameters file.
As the instructions state:
From the Custom deployment blade, navigate to the Edit parameters blade.
From the Edit parameters blade, load the parameters file az-100-01b_azuredeploy.parameters.json.

Let us know if this is not clear enough
rgds
Marcin

**Comment by dmitry86** [comment]
Sorry, my bad. I spent like 3 hours on this, misreading the task. Not sure why I missed that bit. Thanks for your help.

**Comment by polichtm** [comment]
Np - you're welcome...
