### ISSUE TITLE
Missing NSG Rule on VMSS

### ISSUE THREAD

**Issue by lightdrive** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#104]
Module 2 Exercise 3 is missing a step on modifying the NSG to allow internet traffic on port 80, otherwise you can not use the public IP address to verify that IIS was installed and working on the instance.

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/tutorial-create-vmss#allow-traffic-to-application

**Comment by polichtm** [comment]
updated
