### ISSUE TITLE
Module 5 - NSG Not Associated to NIC for VM2

### ISSUE THREAD

**Issue by lightdrive** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#106]
'nic 2' for vm az1000401-vm2 is not associated to the NSG 'az1000401-nsg2' in the template file.

Doesn't affect functionality of lab.

Line 237 - Needs the following adding;

"networkSecurityGroup": {
                    "id": "[resourceId('Microsoft.Network/networkSecurityGroups', variables('networkSecurityGroup1Name'))]"
                }

**Comment by polichtm** [comment]
Can you clarify which file you are referring to?
rgds
Marcin

**Comment by lightdrive** [comment]
Apologies file is "az-100-04_01_azuredeploy.json"

AZ-103-MicrosoftAzureAdministrator-master\Allfiles\Labfiles\Module_05\VNet_Peering_and_Service_Chaining

**Comment by polichtm** [comment]
updated
rgds
Marcin
