### ISSUE TITLE
Lab VM

### ISSUE THREAD

**Issue by ArmandoLacerda** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#108]
Lab 4 refers to a lab VM. None of the previous labs creates a lab VM. Please add a task to create a lab VM for this lab module.

**Comment by polichtm** [comment]
The "lab VM" is simply the computer from which you run the lab. 
The only requirement is that that computer has the Azure PowerShell 1.2.0 or newer installed (as stated at the beginning of lab 4)
rgds
Marcin

**Comment by ArmandoLacerda** [comment]
Understood. Still, there is no instruction for the student to create it on the lab instructions. No exercise 0 or something like that. I understand that having that on the .MD file would avoid confusion. 
As a instructor I tell students what they should do but they get "distracted" sometimes.
