### ISSUE TITLE
Lab VM ip address - bad instructions

### ISSUE THREAD

**Issue by ArmandoLacerda** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#109]
On lab 4, exercise one, task 2, step # 2 says:

> From your lab computer open a Powershell session, run the following in order to identify the public IP address of your lab computer:
> Invoke-RestMethod http://ipinfo.io/json | Select-Object -ExpandProperty IP
> **Note**: Take a note of this IP address. You will use it later in this task.

It does not return the public IP address of the lab computer. It returns the pip of the cloudshell session. 

Suggestion: run it from a new browser tab.

**Comment by polichtm** [comment]
Hi Armando,
would you mind clarifying why you would expect the PowerShell cmdlet running on your computer to return the IP address of the CloudShell session VM (rather than the IP address of your computer)?
rgds
Marcin

**Comment by ArmandoLacerda** [comment]
This is what is happening. Check it out on this short clip: [VM PIP issue](https://recifedev-my.sharepoint.com/:v:/g/personal/me_armandolacerda_com/EeWnOY-esd9Jsk-tsOWIAyUBxn4oqTHEwfXXcSIhlqkdUQ?e=jlzQDE)

**Comment by polichtm** [comment]
Hi Armando,
can you clarify where in the instructions you find a step that states that you should run Invoke-RestMethod http://ipinfo.io/json | Select-Object -ExpandProperty IP
**from the Cloud Shell**?
rgds
Marcin

**Comment by ArmandoLacerda** [comment]
Marcin, see on my first entry: 
On lab 4, exercise 1, task 2, step # 2 says:
>From your lab computer open a Powershell session, run the following in order to identify the public IP address of your lab computer:
>Invoke-RestMethod http://ipinfo.io/json | Select-Object -ExpandProperty IP
>Note: Take a note of this IP address. You will use it later in this task.

**Comment by polichtm** [comment]
Hi Armando,
correct - the instructions state to run a **PowerShell session from your lab computer**

They do **NOT** state to run the command **from the Cloud Session in the browser**

If this is not clear, let us know how you would want to phrase it
rgds
Marcin

**Comment by ArmandoLacerda** [comment]
Marcin, the previous step, step # 1, asks the student to open cloud shell. The next step, step # 2, asks the students to run a PowerShell command. 

You're correct, step # 2 asks the student to open a PowerShell session and run the commands.

In summary:

- Step 1: Cloud Shell (and do nothing there)
- Step 2: Power Shell session (and run a command)
- Step 3: Back to Cloud Shell (and run commands)

I would say it is confusing. I would suggest:

- Step 1: Browse the site ipfinfo.io/json and note the IP address; 
- Step 2: Cloud Shell
- Step 3: run commands (in Cloud Shell)

**Comment by polichtm** [comment]
updated
rgds
Marcin

**Comment by ArmandoLacerda** [comment]
Thanks, Marcin.

**Comment by polichtm** [comment]
You’re welcome…
