### ISSUE TITLE
VNet Peering and Service Chaining instruction ambiguity

### ISSUE THREAD

**Issue by markoshea1212** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#113]
Hi

Exercise 1: Configure VNet peering Task 1 Step 3 instructions don't map directly to updates in the portal

Lab instructions

Allow virtual network access: Enabled
Allow forwarded traffic: disabled

Portal now has settings for both directions for allowing virtual network access and for forwarded traffic settings.

**Comment by polichtm** [comment]
updated
