### ISSUE TITLE
Lab: Configure Azure DNS - PowerShell module/cmdlet change?

### ISSUE THREAD

**Issue by markoshea1212** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#114]
In https://docs.microsoft.com/en-us/azure/dns/private-dns-getstarted-powershell it references a different module - Az.PrivateDns and cmdlet New-AzPrivateDnsZone, as opposed to Exercise 2 Task 2 using New-AzDnsZone with -ZoneType Private.

Not sure if the current lab approach is going to be deprecated, or if I'm looking at two different things.

**Comment by polichtm** [comment]
updated
