### ISSUE TITLE
Lab Module 4 Exercise 2 (Configure Azure DNS for private domains)

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#115]
Cloud Shell does not have the module installed for AzPrivateDNS so not all the cmdlets in this section will work.  Install the module at the beginning of this exercise and the following cmdlets will all work. 

Install-Module -Name Az.PrivateDns -force

Reference - https://docs.microsoft.com/en-us/azure/dns/private-dns-getstarted-powershell

**Comment by polichtm** [comment]
updated

**Comment by steveluper** [comment]
Once the new Az.PrivateDns module is installed, the cmdlets in Ex 2, step 6 need to change to be: 

New-AzPrivateDnsRecordSet -ResourceGroupName $rg2.ResourceGroupName -Name www -RecordType A -ZoneName adatum.local -Ttl 3600 -PrivateDnsRecords (New-AzPrivateDnsRecordConfig -IPv4Address "10.104.0.4")

**Comment by polichtm** [comment]
updated
