### ISSUE TITLE
VM Size Mismatches between Instructions & Templates

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#116]
The VM sizes listed in the instructions do not match the sizes used in the JSON templates for the following:

Module 2 - Instructions say Standard DS2_v2, deploy JSON says Standard_DS1_v2
Module 3 - Instructions say Standard DS2_v2, deploy parameters JSON say Standard_DS1_v2
Module 5 - Instructions say Standard DS2_v2, BOTH deploy JSON say Standard_DS1_v2
Module 8 - Instructions say Standard_D2s_v3, BOTH deploy JSON say Standard_D1s_v2

**Comment by polichtm** [comment]
updated
