### ISSUE TITLE
Alter Removal Instruction Order - Module 9 Lab "Implement Directory Synchronization"

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#121]
Module 9 Lab - Exercise 4 - Please move task 3 - "Delete the Azure AD tenant" to task 1, so students will delete the directory first before deleting the resources.  Many students do not have administrator privileges to launch PowerShell, install the msonline module and perform the steps.  If we do this before removing the virtual machine and other resources, they can run the Powershell commands from the virtual machine before deleting it.

**Comment by polichtm** [comment]
updated
