### ISSUE TITLE
Update JSON Template - Module 2 Lab

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#127]
Hello, 
Located in:  Mod 2, Exercise 1, Step 10 - "From the Custom deployment blade, initiate a template deployment with the following settings:"

Can we please update the actual JSON template so it uses this name as a default? 
Virtual Network Name: az1000301-RG-vnet **(change this value from the template default)**

**Comment by polichtm** [comment]
updated
