### ISSUE TITLE
lab2a ex1 task9-10

### ISSUE THREAD

**Issue by Berrichon** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#129]
to avoid students to encounter an issue while creating their first VM. A step should be added to instruct them to disable boot diagnostic functionality. So their won't be any missing storage in the review process.

Have a nice day ;-)

Louis

**Comment by polichtm** [comment]
Hi Louis,
would you mind clarifying what you mean by "missing storage in the review process"?
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
