### ISSUE TITLE
Additional Step for Module 2 Lab

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#132]
Can we add a step 5 to Module 2 Lab, Exercise 3, Task 2?  

"Click Create"

Some students have told me that they need the reminder for this task.

**Comment by polichtm** [comment]
Hi Mark,
we are trying to avoid the "click through" style of instructions. 
Are you suggesting that students somehow miss clicking the Create button on the Create virtual machine scale set blade? If that is actually the case, the portal will display the notification stating "Your unsaved edits will be discarded". 
rgds
Marcin

**Comment by markturpinMSFT** [comment]
Thanks for updating my understanding!
