### ISSUE TITLE
Module 8 lab template contains different VM size than instructions

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#134]
In mod 8 exercise task 1 step 11, as well as mod 8 task 2 step 10, the instructions state:
Vm Size: use Standard_DS1_v2 or Standard_DS2_v2, based on the instructor’s recommendations

Both templates actually contains DS2_V3. Can we change the template to use DS2_V2?  If not and we need to use DS2_v3, can we please update the instructions to reflect DS2_v3?  Thanks!

**Comment by polichtm** [comment]
updated
