### ISSUE TITLE
Module 2 Lab Error without an extra step 

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#135]
In Module 2 Lab Exercise 1, Task 1 concerning making the first initial Virtual Machine, it errors without going to the Management section to either create a storage account for the Boot Diagnostics or turn it off. I suggest turning it off.  To do this add two steps after Step 9.

Click on Next: Management

Turn off Boot Diagnostics

Then continue with existing step 10 to click on Review + Create

Cheers,
Jeff Smalley
MCT
Chicagoville

**Comment by polichtm** [comment]
Hi Jeff,
the defaults are assigned for a reason - this is the recommended configuration. In my view, students should be aware of it - as well as other management settings. I updated steps to instruct them to review content of both the Management and Advanced tabs. The deployment completes successfully.
Pls let me know if you have any other concerns
rgds
Marcin

**Comment by JeffSmalley** [comment]
I tried the original steps with a fresh new Azure account and it was fine with the original steps.  When doing it with a my normal used account I got the error without going to the Management section. Strange....  

Jeff Smalley

**Comment by tiagocostapt** [comment]
@JeffSmalley I do this all the time in my Azure Subscription and never had issues. Can you share the error that you are getting?

**Comment by JeffSmalley** [comment]
When I try to create the VM I got a validation error on the Management section. When I click back, it wasn't making a Storage Account by default. I would have to manual click "create new" or turn off the Boot Diagnostics.   Weird why it happens with that account.  I also noticed that by default the Auto-shutdown is turned on with that account when I make VMs..  Also strange. Not sure how default behaviors change from one login account to another..
Jeff Smalley

**Comment by polichtm** [comment]
Do you see the same validation error if you actually step through the Management section (rather than skipping it)?
rgds
Marcin

**Comment by markoshea1212** [comment]
Something must have changed in the portal behaviour recently because I got questions around this today, and I didn't get them over the last few deliveries. I'm thinking that maybe the Storage Account for diagnostics field name may have been pre-populated with the newly created one, versus being left blank as it now is.

**Comment by JeffSmalley** [comment]
It seems if I just step thru each section it does make a Storage Account. If after the network section, I jump to the Create and Review it will error with validation with the Management not making the storage account...  I need to do more testing if for some reason it makes a difference with the region I pick...  I did have at least one student have this problem with the labs today..

Jeff

**Comment by polichtm** [comment]
Hi Jeff 
Let us know about the outcome of your testing. This works perfectly fine for me
rgds
Marcin

**Comment by polichtm** [comment]
Hi Jeff,
what was the outcome of your testing?
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
