### ISSUE TITLE
Module 8 Parameter Template Typo causes Fail D

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#136]
The parameter template files az-101-03_01_1_azuredeploy.parameters.json and az-101-03_01_2_azuredeploy.parameters.json  have a typo for the VM size which causes the deployments to fail.....

It states:

"vmSize": {
            "value": "Standard_D2s_v2"
               }

 It should be Standard_DS1_v2 or Standard_DS2_v2 instead...

Happy Teaching!!

Jeff Smalley 
Chicagotown ;)

P.S. I was trying to attach some PNG files to show this but it converts it to text references in my message instead..  Not sure what I am doing wrong with your web interface. I am using Windows 10 and Edge..

**Comment by polichtm** [comment]
updated
