### ISSUE TITLE
10a - Azure AD Identity Protection - portal changes being introduced randomly

### ISSUE THREAD

**Issue by markoshea1212** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#137]
This ties back to closed issue https://github.com/MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator/issues/68

I haven't seen it for a few weeks and now it's back again, but not impacting everyone. It might be too early to update the documentation for the new steps, but it might be worth putting a note in that AAD Security settings in the portal are in transition and steps may alter.

Hopefully the screenshots show the differences.

![1](https://user-images.githubusercontent.com/22210748/67446619-e4f20080-f65c-11e9-947a-299ff3bbfec0.jpg)
![2](https://user-images.githubusercontent.com/22210748/67446620-e4f20080-f65c-11e9-964c-e202d95c0fd6.jpg)
![3](https://user-images.githubusercontent.com/22210748/67446621-e4f20080-f65c-11e9-9d21-f29142214193.jpg)

**Comment by polichtm** [comment]
Would you mind clarifying what specifically are you seeing changing?
rgds
Marcin

**Comment by markoshea1212** [comment]
The AAD blade is occasionally rolling up all of the Security settings into a single link towards the top of the list, instead of Security showing as a category in the list. Today I noticed that there is now the Security Overview (Preview) link that seems to be preparing for that change.

<img width="243" alt="Capture" src="https://user-images.githubusercontent.com/22210748/67529936-538c9800-f709-11e9-84d6-8d10f25d0ab0.PNG">
![image](https://user-images.githubusercontent.com/22210748/67529967-6ef7a300-f709-11e9-91ab-5eeee67a0e07.png)

**Comment by polichtm** [comment]
Which specific set of lab instructions are you concerned about?
rgds
Marcin

**Comment by markoshea1212** [comment]
Some users won't see the Security items list with the MFA option, instead they will need to go back to the top of the list and click on Security, which then takes them to the new blade that will have MFA on it.

**Comment by polichtm** [comment]
Could you provide specific exercise, task, and the step number?
rgds
Marcin

**Comment by markoshea1212** [comment]
Task 5 Step 9 is where this will start causing an issue.

**Comment by polichtm** [comment]
updated
