### ISSUE TITLE
Error in Module_05

### ISSUE THREAD

**Issue by salami738** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#139]
In this module, the command:
Test-NetConnection -ComputerName 10.104.0.4 -TraceRoute
is wrong. It should be:
Test-NetConnection -ComputerName 10.204.0.4 -TraceRoute
because this is the correct ip address in this network.

**Comment by polichtm** [comment]
Are you suggesting that you would want to test the connection of az1-1000402-vm3 to itself? If so, what would be the purpose of it?
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
