### ISSUE TITLE
Password Complexity Issue

### ISSUE THREAD

**Issue by StephenTrap** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#14]
Implement and Manage Azure Web Apps (az-101-02).md file, Excercise 1, Task 3, [Step 5](https://github.com/MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator/blob/master/Instructions/Labs/Implement%20and%20Manage%20Azure%20Web%20Apps%20(az-101-02).md#task-3-configure-web-app-deployment-settings).

The password was not accepted. The complexity requirements state a "minimum of 8 characters and must include a letter and number." It seems that the "." in the password is causing the issue. It accepts the password "Pa55word1234", but will not accept "Pa55w.rd1234". This will effect the rest of the lab where this password is used. Can anyone else confirm this?

**Comment by polichtm** [comment]
Hi Stephen,
this can be any value that is acceptable from the complexity standpoint - which apparently excludes some frequently used passwords. The instructions have been updated to account for that.
rgds
Marcin
