### ISSUE TITLE
Error parsing template. Please ensure template is valid JSON and has no comments.

### ISSUE THREAD

**Issue by svlreddy** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#140]
Unable to save the template. I receive an error "Error parsing template. Please ensure template is valid JSON and has no comments."
Labfiles\Module_11\Governance_and_Compliance\AZ-100.1\az-100-01b_azuredeploy.json

Kindly assist.
![JSON Error](https://user-images.githubusercontent.com/13697758/67552810-657e3300-f729-11e9-8492-fd0f404a3cac.JPG)

**Comment by polichtm** [comment]
Which exercise, task, and step are you referring to and where is this template coming from?
rgds
Marcin

**Comment by svlreddy** [comment]
Dear Marcin,

I have managed to resolve it. Please close the request.

Thank you
