### ISSUE TITLE
Possibly an issue- available vm sizes

### ISSUE THREAD

**Issue by alha3411** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#142]
Has anyone had an issue starting yesterday Oct 24 with the available VM sizes for Azure pass subscriptions changing?  We had numerous errors in class yesterday with VM sizes that were shown as available in Powershell (and that had worked previously) saying they were not available in a region (all US-based)  when actually deploying.

**Comment by polichtm** [comment]
Which VM sizes are you referring to?
Are you able to rerun the same lab today?
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
