### ISSUE TITLE
Markdown Breaking Interpreter

### ISSUE THREAD

**Issue by rlthompson904** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#143]
Exercise 3, Task 3, Step 3
Line 494

3 spaces are used before > **Note**

Causes some interpreters to break showing all of the following substeps to be displayed as one large block

**Comment by polichtm** [comment]
Which lab are you referring to?
Which interpreter(s) are you referring to?
rgds
Marcin

**Comment by rlthompson904** [comment]
This error is in module 2.

Markdown syntax dictates either 4 spaces or tabs used in lists, nested lists, and note blocks https://www.markdownguide.org/basic-syntax/

**Comment by polichtm** [comment]
The intention is indent the note within step 3. 
Would you mind clarifying which interpreters you are referring to?
rgds
Marcin

**Comment by rlthompson904** [comment]
For example the one included with VSCode. Displays as this(Notice the ** visible):

![image](https://user-images.githubusercontent.com/41490785/67914462-949c0680-fb66-11e9-9c1c-ccbd645e6f2b.png)

When it should display as this:

![image](https://user-images.githubusercontent.com/41490785/67914506-bac1a680-fb66-11e9-9509-5db0b72ed19c.png)

**Comment by staleycyn** [comment]
This forum is for Microsoft Certified Trainers. What is the purpose of your request? This course does not use VSCode?

**Comment by rlthompson904** [comment]
It was merely to show an example of how the markdown syntax is incorrect.
