### ISSUE TITLE
Module 02a enhancement

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#146]
When you follow the steps in the lab guide, you run into errors.
Excercise 1:
[Edit: this is not true: From the portal, you need to turn off boot diagnostics, or provide storage account for it.]
When deploying the Ubuntu VMs from the template: the order of the parameters is different. First Image Publisher/Offer/SKU/VM Size, then Vnet name and VNet resourcegroup (which is missing from the lab guide).

**Comment by polichtm** [comment]
Hi Andre, 
here is what I'm seeing in the portal - the name of a new storage account is automatically set. I don't have to "provide" anything.
Are you seeing something different? If so, what is it?

<img width="491" alt="image" src="https://user-images.githubusercontent.com/10284906/68508722-13ff9900-023d-11ea-8d70-ee6f8ce175e2.png">


rgds
Marcin

**Comment by andrePKI** [comment]
Not sure what happened, I must have done something wrong. I cannot reproduce the issue, and in my case also the diagnostic storage account field is populated with a name for a new storage account.

The point about the parameter order is still valid.

**Comment by polichtm** [comment]
updated
