### ISSUE TITLE
Module 03 - small enhancements

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#147]
A few small things to dot the i's and cross the t's (as the response was so quick on my previous comment :-) )
Ex 1 Task 1 Step 4, Access tier parameter not mentioned
Ex 1 Task 1 Step 10, Access tier/Replication parameter order reversed
Ex 1 Task 4 Step 3, it is not necessary to create the container, as azcopy will do this (in fact it will throw an info message in step 5)
Ex 1 Task 5 Step 6: Edge does not prompt for open or save in my case, but display the json contents. Is this default behaviour or is it due to my browser settings? Otherwise the note may be updated

**Comment by staleycyn** [comment]
These labs are for Microsoft training classes which have an instructor present. The labs are not designed for self-study where step by step instructions are needed. Also, please understand although this forum is moderated it is not staffed to provide troubleshooting and help. The content is strictly for Microsoft Certified Trainers to download the latest student materials and report broken steps. You may find help on other forums. Thank you for understanding. Cindy.

**Comment by andrePKI** [comment]
Allright, I'm just putting in my $0,02 to help improve quality. In fact I was directed by my instructor at these resources in preparation.
I am not seeking for help - just helping you.
