### ISSUE TITLE
Module 04: small enhancements: domain/zone name

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#148]
When creating the adatum.local DNS zone, this message is displayed `WARNING: Please be aware that DNS names ending with .local are reserved for use with multicast DNS and may not work as expected with some operating systems. For details refer to your operating systems documentation.`
To avoid confusion about this, wouldn't it be better to use a different tld, like .corp?

**Comment by staleycyn** [comment]
A warning is not an error. As long as the step works as shown, then at this time, it is okay. Thanks,.

**Comment by andrePKI** [comment]
I agree, but still it distracts from the goal of the excercises.
