### ISSUE TITLE
General: reuse  resources between modules?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#149]
When performing all modules in sequence you find you are removing all resources and in the first step of the next module recreating similar resources (most notably VMs). I understand you would want the modules to be executed independently, but still: would it be possible to find a way to make deletion/creation optional (perhaps moving resources to new RGs for naming issues)?

**Comment by staleycyn** [comment]
This has reported before. In future revisions of the course we may consider this strategy. Thank you.
