### ISSUE TITLE
Module 05: copy-paste error

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#150]
By now, you must know what I am doing today ;-)
In module 5, Ex1 Task, step 3:
Allow forwarded traffic from az1000401-vnet1 to az1000402-vnet2: disabled
Allow gateway transit from az1000402-vnet2 to az1000401-vnet1: disabled

Should read
Allow forwarded traffic from az1000402-vnet2 to az1000401-vnet1: disabled
Allow forwarded traffic from az1000401-vnet1 to az1000402-vnet2: disabled

**Comment by polichtm** [comment]
valid point - updated
