### ISSUE TITLE
Module 07:please revise lab manual

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#151]
Maybe this has recently changed in the portal? The V2 in Microsoft.RecoveryServicesV2 may be a hint...
Ex1, Task 2, Step 4 parameter order is different than on the portal. Also a vault is in a region, not location. Order should be:
- Subscription
- Resource group
- Vault name
- Region

Ex 2 Task 1 step 2: I was at a loss where to configure the VM replication. A crucial step is missing: "Click on **Replicate** in order to enable replication."
Next it was not directly clear in step 2 that after selecting the source resource group you have to click ok to go to step 2 and select the VM. I started looking why no VMs were listed...spent some time and started allover again. Until I saw the light and clicked OK after step 1...

**Comment by polichtm** [comment]
updated
