### ISSUE TITLE
Module 09 - add public IP to adVM

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#152]
In order to connect to adVM in Ex 3, Task 1, Step 3 a public IP is necessary, but this is not provisioned from the active-directory-new-domain quickstart template.
Please add a step to add the pip.

**Comment by polichtm** [comment]
Would you mind clarifying what your statement is based on?
The template does include a public IP address resource - that public IP address is assigned to the load balancer in front of adVM. 
Are you stating that you cannot connect to adVM via that public IP address or are you stating that that IP address is not being provisioned?
rgds
Marcin

**Comment by andrePKI** [comment]
When I follow the instructions and download an RDP file, the RDP file contains the private IP, which of course does not work. You can at that time not select a public IP for adVM. This lead to my conclusion that a PIP was missing (I did not notice any load balancer)

**Comment by polichtm** [comment]
That's incorrect. You simply need to select the load balancer IP address (or name):
![image](https://user-images.githubusercontent.com/10284906/68593190-d8deaf00-0462-11ea-8650-8b7e78f27c57.png)

Updated instructions to provide more clarity
rgds
Marcin
