### ISSUE TITLE
Module 11 (first part-RBAC)

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#153]
Ex 1, Task 1 step 5 mentions **Profile** when creating a user. But there is no such field. Also **Name** and **User name** are reversed, while **Password** is before **Groups and roles**. Here too I think the portal has changed since the lab manual was created... I can imagine it is hard to keep up...

**Comment by polichtm** [comment]
updated
