### ISSUE TITLE
Module 12-portal mismatch

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#154]
Ex 1, Task 1, Step 4, I think portal has changed and has different tabs for the parameters; "Allow access from" has become "Connectivity method", some options are added under Advanced tab and Hierarchical namespace cannot be enabled/disabled for this combo of account kind, performance, replication, and location.
In step 7, the Files blade now is File shares blade.
Copy-Paste devil: Ex 1, Task 3 Steps 3 and 4 have the same description.
In Ex 2, Task 1, step 5 there is no list of search results, just a single result. Next in step 6, the blade is named Deploy Azure File Sync and the parameters are in different order.

Ex 2, Task 2, the file to download is now called **StorageSyncAgent_WS2016.msi**

Also, the part about removing the resources is absent

**Comment by polichtm** [comment]
updated
