### ISSUE TITLE
Mod10/Ex 2 - TOR Browser doesn't trigger Identity Protection

### ISSUE THREAD

**Issue by lserpietri** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#155]
Hi Team,

when progressing in the above mentioned exercise, the Tor Browser login attempt triggers a "Low Risk" level event, which will not let Identity Protection block the sign-in attempt as expected. 

As a suggestion, lower the required User Risk from "Medium and above" to "Low".

Thanks!

**Comment by polichtm** [comment]
Hi Luca,
unfortunately the risk level is practically impossible to predict - but your suggestion is valid. Updated accordingly
rgds
Marcin
