### ISSUE TITLE
Module 04: example domain name

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#160]
from [Microsoft documentation](https://docs.microsoft.com/en-us/azure/dns/private-dns-overview):
As a best practice, do not use a .local domain for your private DNS zone. Not all operating systems support this.
So again I suggest to change .local to something like .corp. This avoids an unnessecary and distracting warning. And it is only needed to change this in 1 line in the lab instructions.

**Comment by polichtm** [comment]
updated
