### ISSUE TITLE
Module 09 - Problem with template for AD

### ISSUE THREAD

**Issue by cdanvergara** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#161]
Hello
Reaching out to you as I've tried twice, but experienced the same issue.
I've used the following  the ARM template deployment as specified on the instructions: https://github.com/Azure/azure-quickstart-templates/tree/master/active-directory-new-domain
But it takes longer that 40 minutes and never completes, I had to manually go in the VM and promote it as domain controller.
Anything I'm missing or how can I make sure this run successfully?

**Comment by polichtm** [comment]
Hi Cristian, 
does the deployment fail? If so, what is the error message?
I assume that you are waiting for the DSC extension to complete processing - this might take about 40 minutes. 
If that's the case, choose a larger VM size (try D4s_v3) and let us know about the outcome
rgds
Marcin

**Comment by cdanvergara** [comment]
Hi Marcin, Thanks!
I appreciate the follow-up.
In my case the deployment never ends, I don't get any error message. 
I'll try with a larger VM.

**Comment by polichtm** [comment]
Hi Cristian,
did you have a chance to give this a try?
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response

**Comment by cdanvergara** [comment]
Hi Marcin
Thanks, just a quick comment that I tried myself with a bigger vm DS3_v2 and the deployment took 30 minutes, the script run successfully.
Although, with the same vm size on a class of 20 last week, in 5 cases the script didn't work and we had to install ADDS manually on the vm.
