### ISSUE TITLE
Instruction Change in Module 6 Lab

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#162]
Module 6 Exercise 1 Task 4 Step 11
No more "Firewalls and virtual networks" option on the blade for Azure SQL DB.  It is now a button on top pane "Set Server Firewall" (on the Overview portion of the blade).

**Comment by polichtm** [comment]
Step 11 does not mention "Firewall and virtual networks" option the Azure SQL DB blade. 
It states the following: 
"From the Azure SQL Server blade, navigate to its server's Firewalls and virtual networks blade."
That blade is still called "Firewall and Virtual networks" as per the screenshot below:
![image](https://user-images.githubusercontent.com/10284906/68893134-7dc2eb80-06f2-11ea-8b83-a6ce514b009f.png)


rgds
Marcin

**Comment by markturpinMSFT** [comment]
Ah, thanks Marcin.  Set Server Firewall must be when you drill down to the Database.
