### ISSUE TITLE
Module 11 Lab 2 Correction - Governance and Compliance

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#169]
Exercise 2, Task 2, Step 7 reads:  "Navigate to the blade of the storage account created in the az1000101b-RG - Locks resource group."

I believe the "- Locks" is a typo, as there has been no resource group created with that name.  The resource group that we create in this lab is called "az1000101b-RG"

**Comment by polichtm** [comment]
updated
