### ISSUE TITLE
Module 8 - Task 1 - Both Machines Failed on DSC Extension Install

### ISSUE THREAD

**Issue by tiagoguitar** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#170]
After i submit to create the VM from ARM templates of the Task 1, the Portal Give the following message for BOTH VM´s. 

NOTE: The operation take more than 45 minutes...

Message:

{ "id": "/subscriptions/SUBSCRIPTION_ID/resourceGroups/az1010301-RG/providers/Microsoft.Resources/deployments/Microsoft.Template/operations/F96994C339DB22CF", "operationId": "F96994C339DB22CF", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-11-17T23:36:15.3128944Z", "duration": "PT4M55.1892915S", "trackingId": "882ea0b3-20a3-4a62-b493-fc37cfa2ff4c", "statusCode": "Conflict", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionProvisioningError", "message": "VM has reported a failure when processing extension 'dscExtension'. Error message: \"DSC Configuration 'ContosoWebsite' completed with error(s). Following are the first few: The request to add or remove features on the specified server failed.\r\nInstallation of one or more roles, role services, or features failed.\nThe remote procedure call failed. Error: 0x800706be\n The PowerShell DSC resource '[WindowsFeature]IIS' with SourceInfo 'C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.80.0.0\\DSCWork\\ContosoWebsite.ps1.0\\ContosoWebsite.ps1::8::5::WindowsFeature' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details. Not enough storage is available to complete this operation. \"." } ] } }, "targetResource": { "id": "/subscriptions/f63ddda4-b1b5-4d46-b3ce-e3901f8c5170/resourceGroups/az1010301-RG/providers/Microsoft.Compute/virtualMachines/az1010301w-vm0/extensions/dscExtension", "resourceType": "Microsoft.Compute/virtualMachines/extensions", "resourceName": "az1010301w-vm0/dscExtension" } }}

**Comment by polichtm** [comment]
Pls rerun the lab but this time choose a larger VM size - and let us know about the outcome
rgds
Marcin

**Comment by dpapkin** [comment]
Some of my students, got error msg "Not enough storage to complete this operation" What size should they pick? Examples of sizes to pick would be helpful, thanks

**Comment by dpapkin** [comment]
I have had them use Standard_DS2_V2 successfully.

DP

**Comment by polichtm** [comment]
appreciate the feedback
