### ISSUE TITLE
Lab 8 uses \\ instead of \ 

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#172]
I am using Visual; Studio Code to open these labs, and I have noticed that there is double slashes instead of single slashes

For example:.

ContosoWebsite.ps1\\ContosoWebsite instead of ContosoWebsite.ps1\ContosoWebsite

Regards,

DP

**Comment by polichtm** [comment]
Hi David,
these are markdown escape characters for backslashes (pls refer to your example above)
rgds
Marcin
