### ISSUE TITLE
Lab 7 backup vault security settings

### ISSUE THREAD

**Issue by trayhumphrey** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#173]
Azure recently changed so that new backup vaults have Soft Delete enabled. As a result, any items deleted from the vault are kept for 14 days before destruction. I suggest adding a step in Ex. 1, Task 2 to visit vault Properties / Security Settings to disable Soft Delete before adding in protected items.

**Comment by polichtm** [comment]
Valid point - updated
rgds
Marcin
