### ISSUE TITLE
Module 11 Lab - Risk Events has been renamed Risk Detections

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#175]
Module 11, Lab 1, Exercise 2, Task 4, Steps 17/18

"In the Azure portal, navigate to the Azure AD Identity Protection - **Risk events** blade and note that the entry representing Sign-in from anonymous IP address.

From the Azure AD Identity Protection - **Risk events** blade, navigate to the Azure AD Identity Protection - Users flagged for risk blade and note the entry representing aaduser2"

**Risk Events** is no longer the name of the blade; it has been replaced by "**Risk Detections**"

**Comment by polichtm** [comment]
Hi Mark, 
I gather you meant module 10 - correct?
updated
rgds
Marcin
