### ISSUE TITLE
Error - This is not a valid template (az-100-03_azuredeploy.parameters.json)

### ISSUE THREAD

**Issue by dnguyen92x** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#177]
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "adminUsername": {
            "value": "Student"
        },
        "adminPassword": {
            "value": "Pa55w.rd1234"
        }
    }
}

**Comment by polichtm** [comment]
This is not a deployment template - this is a parameter file.
If you are running into an issue - then make sure to specify the lab, exercise, task, and a step number at which you are seeing this issue
rgds
Marcin
