### ISSUE TITLE
Task 3: Install IIS on a scale set VM using DSC extensions | Code: ProvisioningState/failed/VMExtensionProvisi

### ISSUE THREAD

**Issue by dnguyen92x** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#178]
Hello,

I get this error when attempting Step 3:

From the az1000303vmss0 - Extension blade, add the PowerShell Desired State Configuration extension with the following settings:

---

VM has reported a failure when processing extension 'Microsoft.Powershell.DSC'. Error message: "DSC Configuration 'IISInstall' completed with error(s). Following are the first few: The request to add or remove features on the specified server failed. Installation of one or more roles, role services, or features failed. Not enough storage is available to complete this operation. Error: 0x8007000e The PowerShell DSC resource '[WindowsFeature]IIS' with SourceInfo 'C:\Packages\Plugins\Microsoft.Powershell.DSC\2.80.0.0\DSCWork\az-100-03_install_iis_vmss.1\az-100-03_install_iis_vmss.ps1::5::2::WindowsFeature' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details. The SendConfigurationApply function did not succeed.".
Time
Monday, November 25, 2019, 10:04:09 PM

**Thoughts?**

**Comment by polichtm** [comment]
pls increase the size of VMs in the scale set
rgds
Marcin

**Comment by jgudmundson-RETSD** [comment]
My class also had this issue.  Fix was to reboot the VM and install IIS Manually.

**Comment by dnguyen92x** [comment]
I just ended up deleting everything and restarting the lab. Thanks for the help
