### ISSUE TITLE
Report of virus in this repo

### ISSUE THREAD

**Issue by carlp101** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#179]
FYI,

I downloaded the MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator repo today 26th Nov 2019, and extracted the zip. My AV software detected the following virus infections:

The file ...azure-quickstart-templates-master\matlab-cluster\scripts\public_worker_vm_setup.ps1 is infected with Heur.BZC.PZQ.Boxter.805.888B97A0 and was moved to quarantine. 

The file ...azure-quickstart-templates-master\matlab-cluster\scripts\private_worker_vm_setup.ps1 is infected with Heur.BZC.PZQ.Boxter.805.98F0A3BF and was moved to quarantine.

**Comment by polichtm** [comment]
This error message does not reference files in this repo
rgds
Marcin

**Comment by carlp101** [comment]
Apologies. Wrong repo.
