### ISSUE TITLE
Mod 9: Templated VM AD

### ISSUE THREAD

**Issue by jgudmundson-RETSD** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#180]
The templates VM doesn't auto build ADDS on adVM.

**Comment by jgudmundson-RETSD** [comment]
Correction, it just takes a VERY (30+min) long time plus a manual reboot to make the VM behave as a DC.

**Comment by polichtm** [comment]
That's expected. Pls select a larger VM size - this might shorten the provisioning time
rgds
Marcin
