### ISSUE TITLE
Task 3: Deploy Azure VMs into virtual networks | Step 1 

### ISSUE THREAD

**Issue by dnguyen92x** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#181]
Dumb question, but how do you go about this step below?

In the Cloud Shell pane, upload az-100-04b_01_azuredeploy.json, az-100-04b_02_azuredeploy.json, and az-100-04_azuredeploy.parameters.json files.

I have the files. Not sure how to upload them. Because I get this:

New-AzResourceGroupDeployment : Cannot validate argument on parameter 'ResourceGroupName'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:1 char:50
+ ... urceGroupDeployment -ResourceGroupName $rg2.ResourceGroupName -Templa ...
+                                            ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [New-AzResourceGroupDeployment], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

**Comment by polichtm** [comment]
Just to make sure - are you AZ 103 certified?
Pls refer to https://docs.microsoft.com/en-us/azure/cloud-shell/persisting-shell-storage regarding working with CloudShell
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
