### ISSUE TITLE
Error when creating VM

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#182]
In 02a - Deploy and Manage Virtual Machines (az-100-03).md, in Exercise 1 Task 2 pt. 5, when defining $pip, the allocation method is set to Dynamic. As that will create a PIP with basic SKU it willl not be compatible with the VM created in Task 1, where the PIP is not defined, and therefore creates a PIP with Standard SKU, which only has static allocation. As they are supposed to be in same availability set, the New-VM command will fail.

Therefore the text in Exercise 1 task 1 pt. 8 needs to be extended with a few more points.
Public IP: Click "Create new", leave the default name, change SKU to Basic and the Assignment to Dynamic. Click OK.

**Comment by tekdaemon** [comment]
Hey Tommy, where do you click "create new"? I dont see that option.

**Comment by TommyKobber** [comment]
![Image](https://i.imgur.com/nq0oA0R.jpg)

**Comment by tiagocostapt** [comment]
That happens when you don't fill the required information on the 'Basics' tab. Did you selected the Resource Group and add the Virtual Machine name under the 'Basic' tab?

**Comment by tekdaemon** [comment]
@Tommy-Thanks. Got it!

**Comment by polichtm** [comment]
Hi Tommy,
the instructions work fine for me. Task 1 provisions VMs based on a template which provisions public IP addresses with Basic SKU.
What are you seeing?
rgsd
Marcin

**Comment by TommyKobber** [comment]
I just redid the exercise, this time without errors. I may accidentally have chosen a Standard PIP in the portal. Sorry about wasting your time.
