### ISSUE TITLE
Error connecting via SSH

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#183]
In "02a - Deploy and Manage Virtual Machines (az-100-03).md", Exercise 2 Task 7-11 you're connecting to a Linux VM via SSH. According to the text port 22 should be open by default. This is not the case, so to make this work there should be added a task where port 22 is opened for inbound connections

**Comment by polichtm** [comment]
Hi Tommy,
have you actually tried this? 
As far as I can tell, your assertion is incorrect. 
You are supposed to connect via SSH from a VM on the same VNet. There is no need for opening extra ports since the default security rules suffice.
rgds
Marcin

**Comment by TommyKobber** [comment]
I may have missed a step or 2. I close the case
