### ISSUE TITLE
Error in 08 - Load Balancer and Traffic Manager

### ISSUE THREAD

**Issue by tekdaemon** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#187]
Could not associate Load Balancer with Availability sets in either Resource Group. Did lab 3 times and option to associate with availability set never came up. Ended up just selecting vms. Worked through rest of lab ok. Not sure what issue was. Anybody else have this issue?

**Comment by polichtm** [comment]
Yes - I just rerun the lab and observed the same behavior. The instructions have been updated to reflect that
rgds
Marcin
