### ISSUE TITLE
Lab10b - cannot delete directory

### ISSUE THREAD

**Issue by tekdaemon** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#190]
Anyone able to delete the directory from lab10b? I deleted all enterprise apps but still will not let me delete directory. Says to delete enterprise apps.

How do I delete this directory from this lab?

**Comment by polichtm** [comment]
For starters, make sure that all conditions specified in https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-delete-howto are satisfied
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
