### ISSUE TITLE
Cannot delete storage sync service

### ISSUE THREAD

**Issue by dnguyen92x** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#191]
Microsoft.StorageSync/storageSyncServices/**az1000202b-ss'** could not be deleted. The provisioning state of the resource group will be rolled back. The tracking Id is 'dbd48acc-74bf-4729-87de-6afdba3d62cb'. Please check audit logs for more details. (Code: ResourceGroupDeletionBlocked) Can be deleted only if there are no sync groups in this storage sync service. (Code: MgmtDeletionDependency, Target: Validation) , , , , 

Any thoughts here? I'm out of options.

**Comment by tekdaemon** [comment]
I think I had to remove the server from the sync group and unregister it before it would delete. Check this for more details:  https://docs.microsoft.com/en-us/azure/storage/files/storage-sync-files-server-registration

**Comment by polichtm** [comment]
That's correct.
Let us know how this works out
rgds
Marcin

**Comment by dnguyen92x** [comment]
Yup, that worked. Thanks!
