### ISSUE TITLE
Task 2: Deploy an Azure VM running Windows Server 2016 Datacenter into the existing availability set by using Azure PowerShell

### ISSUE THREAD

**Issue by edmamol** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#200]
HI am getting this error when performing step 4 of Task 2 in Lab02: 
PS Azure:\> $subnetid = (get-AzVirtualNetworkSubnetConfig -Name 'subnet0' -virtualNetwork $vnet).id
**Get-AzVirtualNetworkSubnetConfig : **Cannot bind argument to parameter 'VirtualNetwork' because it is null.****
At line:1 char:79
+ ... zVirtualNetworkSubnetConfig -Name 'subnet0' -virtualNetwork $vnet).id
+                                                                 ~~~~~
+ CategoryInfo          : InvalidData: (:) [Get-AzVirtualNetworkSubnetConfig], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Azure.Commands.Network.GetAzureVirtualNetworkSubnetConfigCommand

I have highlited the error above... what am I missing?

**Comment by polichtm** [comment]
The error implies that $vnet is not set.
Do you have a virtual network named az1000301-RG-vnet ?
rgds
Marcin

**Comment by polichtm** [comment]
resolved via #188 #205
