### ISSUE TITLE
Task 4: Establish service endpoints to an Azure Storage account and Azure SQL Database instance

### ISSUE THREAD

**Issue by asdrubalos** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#203]
12. From the Firewalls and virtual networks blade of the Azure SQL Database server, configure the following settings:

Allow access to Azure services: **OFF**

Recomendations:
from a security point of view
- Settings OFF value and get equals results in tasks lab, olny It allows configured virtual network. (and publics ips assigneds in fw rules)
- No use unnecesary aceess highly permisive in ON all azure

**Comment by andresborjas** [comment]
I agree

**Comment by polichtm** [comment]
Pls clarify which lab and which exercise you are referring to
rgds
Marcin

**Comment by asdrubalos** [comment]
Module 06 - Monitoring
-Exercise 1: Prepare infrastructure for Azure Network Watcher-based monitoring
--Task 4: Establish service endpoints to an Azure Storage account and Azure SQL Database instance
---12.From the Firewalls and virtual networks blade of the Azure SQL Database server, configure the following settings:
----Allow access to Azure services: **OFF**  <----

[https://github.com/MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator/blob/master/Instructions/Labs/06%20-%20Azure%20Network%20Watcher%20(az-101-03b).md](url)

Thanks,

**Comment by polichtm** [comment]
updated
