### ISSUE TITLE
07 - Implement ASR Between Regions (az-101-01).md

### ISSUE THREAD

**Issue by LeonT27** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#204]
Exercise 3: Remove lab resources 
Task 2: Delete resource groups
Need the $ in the variables in **lockedresource** and **lockid**

**Comment by polichtm** [comment]
Hi Leon,
These are not PowerShell variables. Pls make sure to use Bash shell, as per instructions:
Task 1
Step 2
At the Cloud Shell interface, select Bash.
rgds
Marcin
