### ISSUE TITLE
Problem: Lab:Configure Azure DNS, Exercise 2, Task 2, Step 1 #188

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#205]
This issues was raised and closed due to lack of response earlier.  It is still an issue..   

This entry fails:
vnet1link = New-AzPrivateDnsVirtualNetworkLink -ZoneName $zone.Name -ResourceGroupName $rg2.ResourceGroupName -Name "vnet1Link" -VirtualNetworkId $vnet1.id -EnableRegistration

Error:
New-AzPrivateDnsVirtualNetworkLink : Cannot validate argument on parameter 'VirtualNetworkId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:1 char:148
+ ... sourceGroupName -Name "vnet1Link" -VirtualNetworkId $vnet1.id -Enable ...
+                                                         ~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [New-AzPrivateDnsVirtualNetworkLink], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.PrivateDns.VirtualNetworkLinks.NewAzurePrivateDnsVirtualNetworkLink

I would also suggest dropping the "Install-Module -Name Az.PrivateDns -force"

It works fine without it..

This was an Old issue that was closed. Not sure if I could re-open it so I just opened a new issue.

Regards,
Jeff Smalley MCT
Chicagoville

**Comment by polichtm** [comment]
Hi Jeff,
this works perfectly fine for me:
PS Azure:\> $vnet1 = Get-AzVirtualNetwork -Name az1000402b-vnet1
Azure:/
PS Azure:\>
Azure:/
PS Azure:\> $vnet2 = Get-AzVirtualNetwork -name az1000402b-vnet2
Azure:/
PS Azure:\> $zone = New-AzPrivateDnsZone -Name adatum.corp -ResourceGroupName $rg2.ResourceGroupName
Azure:/
PS Azure:\> $vnet1link = New-AzPrivateDnsVirtualNetworkLink -ZoneName $zone.Name -ResourceGroupName $rg2.ResourceGroupName -Name "vnet1Link" -VirtualNetworkId $vnet1.id -EnableRegi
stration
Azure:/
PS Azure:\>
![image](https://user-images.githubusercontent.com/10284906/73123942-6199c100-3f63-11ea-9cd5-b4e2cb8eea60.png)

Have you verified that vnet1 actually exists?
rgds
Marcin
