### ISSUE TITLE
Module 11 Lab on Role Based Access Control

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#206]
It looks like in Exercise 2, the GitHub template gallery, the 101-vm-simple-linux  template switch the VM Size to a Parameter. Therefore 2 steps need to be changed.

Task 2, Step 2: replace "Variables" section to "Parameters" section.

Task 3, Step 2: it should say now, "On the Edit Parameters blade, locate the vmSize entry."   It shouldn't be "Edit the Template". 

Happy Teaching,
Jeff Smalley MCT
Chicagoville

**Comment by polichtm** [comment]
Hi Jeff 
updated
rgds
Marcin
