### ISSUE TITLE
Module 11 Lab on Implementing governance and compliance

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#207]
This not a bug but a suggestion. This lab creates 2 VMs. None of these VMs are used. I would add a note in the instructions that the students can stop and deallocate them at anytime to save money since they are not used for anything.  A more involved change would be to create them via the templates in a stopped state or maybe just not create a VM in the first place. That lab is all about adding tags to something. A VM is not really needed.  

Again not a big deal here but just a thought..

Cheers,
Jeff Smalley MCT
New Chicago

**Comment by polichtm** [comment]
Hi Jeff,
appreciate the suggestion - this is a valid point - an updated lab is in the works...
rgds
Marcin
