### ISSUE TITLE
unable to create a private dns name in task 2 lab 4 

### ISSUE THREAD

**Issue by germeister2019** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#209]
hi there , I am unable to create a privater dns zone in the powershell provided 👍 powershell = 

PS Azure:\> $vnet1link = New-AzPrivateDnsVirtualNetworkLink -adatum.corp $zone.Name -1-00c21c-playground-sandbox $rg2.ResourceGroupName -Name "vnet1Link" -az1000402b-vnet1$vnet1.id -EnableRegistration
New-AzPrivateDnsVirtualNetworkLink : A parameter cannot be found that matches parameter name 'adatum'.
At line:1 char:49
+ $vnet1link = New-AzPrivateDnsVirtualNetworkLink -adatum.corp $zone.Na ...
+                                                 ~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [New-AzPrivateDnsVirtualNetworkLink], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.PrivateDns.VirtualNetworkLinks.NewAzurePrivateDnsVirtualNetworkLink

can someone please advise on this ?

**Comment by polichtm** [comment]
Pls make sure to follow the instructions

$vnet1 = Get-AzVirtualNetwork -Name az1000402b-vnet1

$vnet2 = Get-AzVirtualNetwork -name az1000402b-vnet2

$zone = New-AzPrivateDnsZone -Name adatum.corp -ResourceGroupName $rg2.ResourceGroupName

$vnet1link = New-AzPrivateDnsVirtualNetworkLink -ZoneName $zone.Name -ResourceGroupName $rg2.ResourceGroupName -Name "vnet1Link" -VirtualNetworkId $vnet1.id -EnableRegistration

hth
Marcin

**Comment by germeister2019** [comment]
I am using a sandbox and not say a trial subscription from azure , would this be the issue ?

**Comment by germeister2019** [comment]
guys am I doing something silly here 👍 
trying to New-AzResourceGroupDeployment -1-f1e17e-playground-sandbox $rg2.1-f1e17e-playground-sandbox -TemplateFile "./az-100-04b_01_azuredeploy.json" -TemplateParameterFile "./az-100-04_azuredeploy.parameters.json" -AsJob

and getting :  At line:1 char:65
+ ... -AzResourceGroupDeployment -1-f1e17e-playground-sandbox $rg2.1-f1e17e ...
+                                                                  ~
Missing property name after reference operator.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : MissingPropertyName


am not using the resource group in the labs but using a sandbox one , any advise ?

**Comment by staleycyn** [comment]
Hello germeister2019. This repository is for Microsoft Certified Trainers who are teaching Microsoft courseware. We use the repo to distribute classroom labs. We are not staffed to answer questions like this. I hope you understand.
