### ISSUE TITLE
Lab Load Balancer and Traffic Manager error

### ISSUE THREAD

**Issue by GerardoAttardi** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#21]
When performing Exercise 0: Deploy Azure VMs by using Azure Resource Manager templates

Deployment finishes with error

{ "id": "/subscriptions/17f64fae-f252-4eb8-ba1a-8423f32e887c/resourceGroups/az1010301-RG/providers/Microsoft.Resources/deployments/Microsoft.Template/operations/F31930E7D34FD0F5", "operationId": "F31930E7D34FD0F5", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-05-28T21:05:11.8445311Z", "duration": "PT4M15.1396864S", "trackingId": "78775c7a-8cbb-4987-aff0-33e47fe99eee", "statusCode": "Conflict", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionProvisioningError", "message": "VM has reported a failure when processing extension 'dscExtension'. Error message: \"The DSC Extension failed to execute: Cannot process argument transformation on parameter 'ConfigurationFunction'. Cannot convert value to type System.String..\nMore information about the failure can be found in the logs located under 'C:\\WindowsAzure\\Logs\\Plugins\\Microsoft.Powershell.DSC\\2.77.0.0' on the VM.\"." } ] } }, "targetResource": { "id": "/subscriptions/17f64fae-f252-4eb8-ba1a-8423f32e887c/resourceGroups/az1010301-RG/providers/Microsoft.Compute/virtualMachines/az1010301w-vm1/extensions/dscExtension", "resourceType": "Microsoft.Compute/virtualMachines/extensions", "resourceName": "az1010301w-vm1/dscExtension" } }}

**Comment by polichtm** [comment]
Hi Gerardo, 
pls ensure that the Configuration Function is set to ContosoWebsite.ps1\ContosoWebsite (that's the way it should appear in the Azure portal when you perform the template deployment). 
rgds
Marcin

**Comment by GerardoAttardi** [comment]
Hi polichtm! Thank you for your quick answer.... yes... it appears just like that:

ContosoWebsite.ps1\ContosoWebsite

And it does not work. Always the same error

I have tried a few things for example "ContosoWebsite.ps1\ContosoWebsite".... but nothing.... it keeps failing with the same error......

**Comment by polichtm** [comment]
Hi Gerardo
for clarity sake - once you load the template file and the parameters file, you should not have to modify any parameters. All you have to do is create a new resource group and select the target Azure region. Is this the case?
I just ran this deployment and completed without any issues. 
rgds
Marcin

**Comment by GerardoAttardi** [comment]
Hi.... it is hard to believe that it works for you.

To be clear:
I load the template file and parameters file, I DO NOT modify any parameters. I JUST create the NEW RESOURCE GROUP (az1010301-RG) and select region (East US)

And it fails with the error I just posted in my first post......

Could it be the region? Which region are you using.....?

I am an MCT.... I will deliver this course next week.... and I am testing each lab just to be shure.... this is not the first error I found... but this is the one I cannot solve myself

**Comment by polichtm** [comment]
Hi Gerardo,
I'm also deploying to EastUS… ;)
Can you download the repo again and use the parameter files from it?
rgds
Marcin

**Comment by polichtm** [comment]
Hi Gerardo,
one more suggestion - the error seems to indicate an issue with the format of Configuration Function, but could you also try increasing the size of the Azure VMs you are deploying (e.g. Standard_D2s_v3)?
rgds
Marcin

**Comment by GerardoAttardi** [comment]
Thanks a lot for your help, I have already deleted Github Repo in my computer and downloaded it again from scratch --> error persists.

I will try again with a bigger VM, will use Standard_D2s_v3 as you suggested.... and let you know in a few minutes....

**Comment by GerardoAttardi** [comment]
And it worked!!!!!! Using a bigger VM: Standard_D2s_v3

Could it be a "timedout" issue????? I do not find another explanation....

(Changed another thing as well: I was using Chrome and this time I used Edge.... I think  it does not have anything to do with the issue anyway...)

**Comment by polichtm** [comment]
HI Gerardo,
good to see. I'll update the instructions accordingly
rgds
Marcin
