### ISSUE TITLE
Module 10 Lab: Azure AD Identity Protection

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#212]
Since this lab is only configuring one VM I would increase the Size of it.  It is very buggy with the low settings.  I certainly understand labs where we run 4 VMs on making the size lower but this is just one.

Couple Step changes...

Exercise 1, Task 2, Step 5

It states "From the Licenses - All products blade, navigate to the Activate blade and activate Azure AD Premium P2 free trial." I find this very confusing on where to go. I would state, "From the Licenses - All products blade, click on Try/Buy Button and click Free Trial of Azure AD Premium P2, then click Activate."

Exercise 1, Task 5, Step 9
The labels are different that the current instructions: I would state:  : "From the AdatumLab101-4b - Overview blade, navigate to the Security blade, then MFA blade."

Also, at the end of Exercise 2, Task 4, the names of blades in Azure AD Identity Protection are mainly different than what the instructions have. Unfortunately I am too swamped to list them. 

I do have a PowerPoint deck with the screen shots of this lab if you want to see it I can upload it to you. Actually I have screen shot PowerPoint decks of all the labs I can send you if you want to use as a reference. 

Happy Azure world,
Jeff Smalley
Chi-Town

**Comment by polichtm** [comment]
Hi Jeff,
would you mind uploading the PowerPoint deck you are referring to?
rgds
Marcin

**Comment by JeffSmalley** [comment]
[AZ-103 Module 10 Lab A Screen Shots.pptx](https://github.com/MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator/files/4140530/AZ-103.Module.10.Lab.A.Screen.Shots.pptx)


I have these PPT decks for each labs.  Let me know if you want them..  Any instructor is welcome to use them..

Ciao Baby,
Jeff Smalley MCT
Chicagovill

**Comment by azharkhuwaja** [comment]
Hi Jeff,
can I have those PPT decks for all labs? It will help my students greatly.

Appreciate it.
Azhar

**Comment by polichtm** [comment]
updated
