### ISSUE TITLE
Module 10 Lab B: Self-Service Password Reset

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#214]
Here are a few changes I saw today....

Exercise 1, Task 2, Step 5: It states: "From the Products blade, navigate to the Activate blade and activate Azure AD Premium P2 free trial." I believe it should be "From the Licenses - All products blade, click on Try/Buy Button and click Free Trial of Azure AD Premium P2, then click Activate."

Exercise 1, Task 5, Step 2: I would eliminate the "Simple Rule" reference since that is not on the portal interface anymore.

Exercise 1, Task 5, Step 3: I would eliminate the "Advanced rule" reference since it not on the portal interface anymore. I would just state: "Add users where: (user.department -eq “Sales”) -or (user.department -eq “Finance”)"

Exercise 2, Task 2, Step 1: It states "From the Microsoft OneDrive - Overview blade, navigate to the Microsoft OneDrive - Getting started blade."
The "Getting Started" section has moved to Overview blade now.  It should now state: "On the Overview blade, select Set up single sign on." 
Exercise 2, Task 2, Step 2: Delete since covered now in step 1.

Exercise 2, Task 3, Steps 1 and 2 should be combined. There is no "Assign a user for testing (required) option" anymore. The step should read: "Navigate to the Overview blade, click 1. Assign users and groups."

Also, this lab has no clean up steps. Here is the basic I have:

Clean Up – 
1. Log back into portal.azure.com as main class login account
2. Add one of the new user accounts to Global Administrator Role
3. Log in as that user
4. Delete all other uses in new Tenant domain
5. Delete all created groups
6. Delete the Enterprise App Registration
7. Cancel and then Delete the Premium P2 license-based subscriptions (takes 72 hours)
   Link to this is listed when you try to delete the Directory
8. Add Permissions to Global Admin role account to allow Domain deletions
   Link to this is listed when you try to delete the Directory
9. Log back in after 72 hours and delete the lab’s Azure Directory Domain

The times they are a changin'

Cheers,
Jeff Smalley MCT
Chicagoville

**Comment by polichtm** [comment]
Hi Jeff,
appreciated 
rgds
Marcin
