### ISSUE TITLE
Module 4

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#215]
Having error running this.
I had to add www record from portal to make it work.

#251 New-AzPrivateDnsRecordSet -ResourceGroupName $rg2.ResourceGroupName -Name www -RecordType A -ZoneName adatum.corp -Ttl 3600 -PrivateDnsRecords (New-AzPrivateDnsRecordConfig -IPv4Address "10.104.0.4")

Any help?
Thanks

**Comment by polichtm** [comment]
Pls provide the lab number, the exercise, task and the error message
rgds
Marcin
