### ISSUE TITLE
Spelling mistake & change to OneDrive?

### ISSUE THREAD

**Issue by faceboogle** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#217]
Hello

Thanks for the work done with these labs. Two things that might be improved...

Exercise 1 / Task 6 / Step 4
Password reset - _Auhentication_ methods (should be "au_t_hentication"?)

Exercise 2 / Task 3 / Step 2
Assign Credentials: ("Assign Credentials" not found, is this still possible with OneDrive?)

Cheers

**Comment by polichtm** [comment]
What specifically do you mean by "not found" ?
![image](https://user-images.githubusercontent.com/10284906/74492543-31c44600-4e9d-11ea-8ddf-9122e145421f.png)

rgds
Marcin
