### ISSUE TITLE
Lab: Implement Directory Syncronization ADSyncSyncCycle Powershell Command

### ISSUE THREAD

**Issue by XtremeDR** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#22]
In the Lab Implement Directory Synchronization in Exercise 3, Task 3 the user is asked to run the following powershell command in the adVM virtual machine:

 Start-ADSyncSyncCycle -PolicyType Delta

Running this command without first importing the adsync module will fail, and I can't find any directions for doing that in the lab instructions.  It may be advisable to add a step to run the command to import the module to the steps:

import-module -name 'c:\Program files\Microsoft azure ad sync\bin\adsync'

**Comment by polichtm** [comment]
updated
rgds
Marcin
