### ISSUE TITLE
Missing $ sign in Lab 07 instructions

### ISSUE THREAD

**Issue by koenraadhaedens** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#228]
Original : 

lockedresource=$(az resource list --resource-group az1010101-RG-asr --resource-type Microsoft.Compute/disks --query "[?starts_with(name,'az10101')].name" --output tsv)
az disk revoke-access -n $lockedresource --resource-group az1010101-RG-asr
lockid=$(az lock show --name ASR-Lock --resource-group az1010101-RG-asr --resource-type Microsoft.Compute/disks --resource-name $lockedresource --output tsv --query id)
az lock delete --ids $lockid
az group list --query "[?starts_with(name,'az10101')].name" --output tsv | xargs -L1 bash -c 'az group delete --name $0 --no-wait --yes'

should be :
$lockedresource=$(az resource list --resource-group az1010101-RG-asr --resource-type Microsoft.Compute/disks --query "[?starts_with(name,'az10101')].name" --output tsv)
az disk revoke-access -n $lockedresource --resource-group az1010101-RG-asr
$lockid=$(az lock show --name ASR-Lock --resource-group az1010101-RG-asr --resource-type Microsoft.Compute/disks --resource-name $lockedresource --output tsv --query id)
az lock delete --ids $lockid
az group list --query "[?starts_with(name,'az10101')].name" --output tsv | xargs -L1 bash -c 'az group delete --name $0 --no-wait --yes'

**Comment by polichtm** [comment]
Pls make sure to use Bash - not PowerShell - as per instructions
rgds
Marcin
