### ISSUE TITLE
Quota error on task 3 of Deploy and Manage Virtual Machines

### ISSUE THREAD

**Issue by gpend** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#229]
I am getting an error stating that I will exceed my core quota if I complete the purchase. this occurs at the end of 'Task 3: Deploy two Azure VMs running Linux into an availability set by using an Azure Resource Manager template'

**Comment by dpapkin** [comment]
You need to open a Support ticket to change the subscription limit to 20 cores .It is free, will have the new limit within an hour automatically, alternatively, run it in a different region that you havent deployed anything . David Papkin

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by polichtm** [comment]
Hi Greg,
If you/your students are using Azure Pass subscriptions dedicated for this course, then you should delete any VMs that are not part of the current lab. Processing quota increase requests might take more than an hour. As David mentioned, you might also opt to use another region. 
This is a side effect of increasing sizes of the VMs provisioned in the labs of this course, which was requested by a number of MCTs.
rgds
Marcin

**Comment by dpapkin** [comment]
Hi Greg,

Here is a screencap how to open a service request to increase Compute cores, It is good to show this to your students, is an important skill for them to know.

David Papkin


[cid:image003.png@01D5F093.11D4B8B0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
