### ISSUE TITLE
Lab File Sync Module Powershell Need az.resources in RDP session VM

### ISSUE THREAD

**Issue by XtremeDR** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#23]
When running the Azure File Sync Agent setup in the Implementing File Sync module in Exercise 2 Task 3 the operation will fail after selecting the user subscription with an error stating that it does not know how to handle the Get-AzResourceGroup command.  The user will need to install the az.resources module when installing the other pre-requisite modules in Powershell earlier in the lab to resolve this issue.  I recommend adding the following line of powershell during the pre-req install section in Exercise 2, Task 2:

Install-Module -name az.resources

**Comment by polichtm** [comment]
resolved
rgds
Marcin
