### ISSUE TITLE
az cloud bash prompt not deleting RG

### ISSUE THREAD

**Issue by Maygus** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#233]
I followed the lab to delete the 2 RGs created during this process, however it was not successful.
I ended up deleting manually via Azure interface.

The final line I ran about 5-10 minutes later to see if it had processed and RGs still there, no action I could see taken in the browser.
![image](https://user-images.githubusercontent.com/6929584/76268736-21985e80-62c3-11ea-9065-fe9af8562f04.png)

**Comment by polichtm** [comment]
You might have to wait longer
Added a note to the instructions to account for delay/the need to rerun the command
rgds
Marcin
