### ISSUE TITLE
MODULE 10 Lab – Azure AD Identity Protection - ISSUE

### ISSUE THREAD

**Issue by GerardoAttardi** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#24]
Execise 1, Task 5, Step 3:

"Call to phone" verification OPTION is dimmed (grayed out) and cannot be selected.

Inside "Multifactor Authentication / Service Settings" It is not possible to select CALL TO PHONE OPTION.... then.... Task 6, Step 5 cannot be done.....

Appreciate your help

Thank you!

**Comment by GerardoAttardi** [comment]
I figured out WHY....... 

In this link: https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-authentication-methods

You can find this:

"Phone call
An automated voice call is made to the phone number you provide. Answer the call and press # in the phone keypad to authenticate

 Important

Starting in March of 2019 the phone call options will not be available to MFA and SSPR users in free/trial Azure AD tenants. SMS messages are not impacted by this change. Phone call will continue to be available to users in paid Azure AD tenants. This change only impacts free/trial Azure AD tenants."

PLEASE UPGRADE THE LABS STEP... IT IS A DISGRACE THAT LABS ARE ALWAYS LATE TO AZURE CHANGES!!!!!!!!! IT is impossible to deliver courses like this....... Labs need to be smooth..... this goes against student satisfaction....  this is not professional at all

**Comment by polichtm** [comment]
Hi Gerardo,
given the pace of changes in Azure, keeping lab instructions up to date constitutes a fairly significant challenge. 
Appreciate pointing out the issue - and identifying its cause. The update will be applied shortly
rgds
Marcin

**Comment by GerardoAttardi** [comment]
Hi Marcin... I know that it is difficult.... but not impossible.... I think that labs need to be updated every time the platform is updated so instructors and students are not guided through outdated steps.... (I am saying this with respect).

**Comment by polichtm** [comment]
updated
