### ISSUE TITLE
Lab On Demand is telling students to use GitHub

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#242]
Marcin, This is at the start of the first **AZ-103 Lab**:
![image](https://user-images.githubusercontent.com/20519564/77240388-4c33c280-6bb3-11ea-8889-5d854a85cde1.png)

I raised a support request with them (I am an MCT at New Horizons in the US) and this is their response:

> LODS Help Desk Team <support@learnondemand.zendesk.com>
> 3/17/2020 11:37 AM
> 
> RE: AZ103T00 lab directs students to the MCT GitHub site to report errors! (Ticket 148241)
> 
>  	Ronald Thompson (LODS) 
> Mar 17, 12:37 PM EDT 
> Hi Eric,
> 
> The disclaimer is used when we pull directions directly from GitHub. This has been implemented per direction from Microsoft. We will be unable to remove the link from the labs. 
> Thanks,
> Ronald Thompson
> Technical Services Tier-2
> 
> Ticket number #148241 has been marked as solved and will close in 5 days.
> Should you require further assistance with this request, please respond to this ticket within 5 days, after which time a new support ticket request is required.
> If you have a different type of support request, please submit a new support ticket at https://www.learnondemandsystems.com/customer-support/. 
> Thank you,
> Learn on Demand Systems
This is not really an issue with this lab, just letting you know why there are so many students raising issues in here. (And someone might want to talk to LOD about it.)

**Comment by polichtm** [comment]
Hi Eric, 
appreciated. I'll follow up regarding this...
rgds
Marcin
