### ISSUE TITLE
Add link to Business store for cleaning up AAD P2 trial

### ISSUE THREAD

**Issue by Tuumke** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#243]
When you have to clean up your labs, for example Lab 10b Excercise 3, you have to remove your AzureAD directory. But in order to do so, you need to have:
- A Global Admin that is not your tentant account
- All the other regular stuff
- Cancel and delete your AAD P2 trial using the store for businesses: https://go.microsoft.com/fwlink/?linkid=2101580

Took me ages to find this and complete my labs..

**Comment by polichtm** [comment]
Are you referring to the lab 10a?
The the lab instructions already include the following:



    Note: To remove the Azure AD tenant you created in this lab, follow https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-delete-howto

Pls advise what specifically you would want to include in the instructions
rgds
Marcin

**Comment by Tuumke** [comment]
Well yes, i followed those instructions. But it wouldnt let me delete the AAD directory from the lab. I had to go to the URL i posted and cancel, then delete dhe P2 trial

**Comment by polichtm** [comment]
updated
rgds
Marcin
