### ISSUE TITLE
Azure Pass not able to create resources

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#244]
It appears that the free Azure Pass accounts cannot create resources right now (3/27)--is there any statement from Microsoft on this? Any suggestions for a work-around?

**Comment by staleycyn** [comment]
Please join the discussion on the MCT Courseware Forum. You can read about how [Azure is prioritizing resources for critical/important functions](https://azure.microsoft.com/en-us/blog/our-commitment-to-customers-and-microsoft-cloud-services-continuity/). And, there is the[ Important Update on Microsoft Training and Certification](https://www.microsoft.com/en-us/learning/community-blog-post.aspx?BlogId=8&Id=375289).

**Comment by itbland** [comment]
Thanks
