### ISSUE TITLE
Cannot validate argument on parameter 'Name'.

### ISSUE THREAD

**Issue by mirali1** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#247]
Hi,

I am trying to run following PS command as part of AZ lab exercise and getting error message. Can anyone can help on this. Thanks

$storageAccount2Key1 = (Get-AzStorageAccountKey -ResourceGroupName 'az1000203-RG' -StorageAccountName $storageAccount2Name)[0].Value

Get-AzStorageAccountKey: Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

**Comment by renaudwangler** [comment]
Hello.

As stated in you error message, the "$storageAccount2Name" variable is empty...
Cannot help much more without context ;)

**Comment by mirali1** [comment]
Hi, Thanks for your reply. I ran similar PS command and it ran successfully. Sorry if asked silly Qs I am new to the PS so not sure about it. 

$storageAccount1Key1 = (Get-AzStorageAccountKey -ResourceGroupName 'az1000202-RG' -StorageAccountName $storageAccount1Name)[0].Value

**Comment by mirali1** [comment]
Here is whole PS commands part of the LAB.

$containerName = 'az1000202-container'
$storageAccount1Name = (Get-AzStorageAccount -ResourceGroupName 'az1000202-RG')[0].StorageAccountName
$storageAccount2Name = (Get-AzStorageAccount -ResourceGroupName 'az1000203-RG')[0].StorageAccountName
$storageAccount1Key1 = (Get-AzStorageAccountKey -ResourceGroupName 'az1000202-RG' -StorageAccountName $storageAccount1Name)[0].Value
$storageAccount2Key1 = (Get-AzStorageAccountKey -ResourceGroupName 'az1000203-RG' -StorageAccountName $storageAccount2Name)[0].Value
$context1 = New-AzStorageContext -StorageAccountName $storageAccount1Name -StorageAccountKey $storageAccount1Key1
$context2 = New-AzStorageContext -StorageAccountName $storageAccount2Name -StorageAccountKey $storageAccount2Key1

**Comment by mirali1** [comment]
got it fixed, ran the whole PS commands at once and it was successful :) Thanks
