### ISSUE TITLE
Can't execute the Script in both Az Cloud Shell or Powershell 7 at my own PC

### ISSUE THREAD

**Issue by SAIMMINHAS** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#250]
Hi guys,

Would really appreciate if you can please help me. I'm not sure where i'm doing something wrong but it seems that i can't run the script in either Az Cloud Shell or in the Powershell 7 at my own PC. Funny thing is that, when i copy and paste the script, it's showing a red color ' > ' symbol before the ' { ' symbol which means something is wrong. I'm new to Github and below is what i'm getting:

1. Error when the script is run in Az Cloud Shell:
ParserError:
Line |
   2 |      "$schema": "https://schema.management.azure.com/schemas/2015-01-0 …
     |               ~
     | Unexpected token ':' in expression or statement.

2. Error when the script is run in Powershell 7 at my own PC:
ParserError:
Line |
   2 |      "$schema": "https://schema.management.azure.com/schemas/2015-01-0 …
     |               ~
     | At line:2 char:14 +     "$schema": "https://schema.management.azure.com/schemas/2015-01-0 … +              ~
Unexpected token ':' in expression or
     | statement.  At line:5 char:16 +        "vmSize": { +                ~
Unexpected token ':' in expression or statement.  At line:6 char:17 +
     | "type": "string", +                 ~
Unexpected token ':' in expression or statement.  At line:8 char:27 +              "description": "Virtual machine
     | size" +                           ~
Unexpected token ':' in expression or statement.  At line:12 char:17 +           "type": "string", +                 ~
     | Unexpected token ':' in expression or statement.  At line:15 char:27 +              "description": "VM name" +                           ~
Unexpected token
     | ':' in expression or statement.  At line:19 char:18 +            "type": "string", +                  ~
Unexpected token ':' in expression or statement.
     | At line:21 char:28 +               "description": "Admin username" +                            ~
Unexpected token ':' in expression or statement.  At
     | line:25 char:18 +            "type": "securestring", +                  ~
Unexpected token ':' in expression or statement.  At line:27 char:29 +
     | "description": "Admin password" +                             ~
Unexpected token ':' in expression or statement.  Not all parse errors were reported.
     | Correct the reported errors and try again.

**Comment by ITBlandMCT** [comment]
JSON files are not PowerShell, they are Azure Templates. You need to do a custom deployment from the portal, per the lab instructions.

**Comment by ITBlandMCT** [comment]
Issues here are for reporting errors or changes in the lab, for student support, please ask your trainer!

**Comment by SAIMMINHAS** [comment]
Gotcha..many thanks.. ITBlandMCT
