### ISSUE TITLE
The last task 'Delete resource groups' is not deleting the resource groups

### ISSUE THREAD

**Issue by SAIMMINHAS** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#251]
Hi,

For some reason, the last task 'Delete resource groups' is not deleting the resource groups. I'm using the following command as advised in the lab instructions:

az group list --query "[?starts_with(name,'az100010')].name" --output tsv | xargs -L1 bash -c 'az group delete --name $0 --no-wait --yes'

**Comment by azharkhuwaja** [comment]
It takes 10 minutes or longer in some cases for resource groups to disappear from Portal.

You can try this Powershell script;
Get-AzResourceGroup -Name "az100*" | Remove-AzResourceGroup -Verbose -Force

**Comment by SAIMMINHAS** [comment]
Hi Azhar

Many thanks.
