### ISSUE TITLE
Incorrect Step in 09 Lab

### ISSUE THREAD

**Issue by lathishsundar** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#253]
In **Lab 09, Ex3-> Task 1-> Step 6, 7 and 8,** it required the organization unit to be created under _**'Active Directory Administrative Unit'**_. However, there is no option to create a new unit in this App. The instructions should be modified to create a new organization unit in **_'Active Directory Users and Computers'_**.

**Comment by renaudwangler** [comment]
Please don't tell your student to use the prehistoric "Active Directory Users and computers" tool :)
The 'Active Directory Adminstrative Center" is so much more usefull and made for day to day administrative tasks. If you don't know how to create an OU, find any tutorial on the net that'll show you how to do it in a much more efficient way as using the old tool (sample here : https://docs.microsoft.com/en-us/azure/active-directory-domain-services/create-ou) ;)

**Comment by lathishsundar** [comment]
@renaudwangler Thank you. I am new to Windows Administration. I am not familiar with these functions.
