### ISSUE TITLE
4 labs not being part of the AZ-103 course:

### ISSUE THREAD

**Issue by SAIMMINHAS** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#255]
Hi,

The repository for 'AZ-103-MicrosoftAzureAdministrator' says that the following labs will not be part of the AZ-103 course:

1. Azure Event Grid and Azure Logic Apps (az-101-02b)
2. Implement and Manage Azure Web Apps (az-101-02)
3. Migrate On-premises Hyper-V VMs to Azure (az-101-01b)
4. Privileged Identity Management (az-101-04)

Does that mean these topics will not appear in the Az-103/104 exam or is there any alternative for these labs?

Thanks for the clarification.

**Comment by ITBlandMCT** [comment]
Always refer to the Exam page: [Exam AZ-103: Microsoft Azure Administrator](https://docs.microsoft.com/en-us/learn/certifications/exams/az-103) and the downloadable [Skills measured](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE3VwUR) file for what is (or is not) on an exam.
You should also work thru [LEARNING PATH: Administer infrastructure resources in Azure](https://docs.microsoft.com/learn/paths/administer-infrastructure-resources-in-azure/), as the classes never cover 100% of the Skills required to pass an exam.

**Comment by SAIMMINHAS** [comment]
Ok..Thanks...
