### ISSUE TITLE
Module 11B Error and Suggestion

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#26]
In Module 11 Lab B, Exercise 1, Task 3, Step 4: The built-in policy definition that is to be added is named wrong in the lab steps. It is listed as "Enforce tag and its value". It should be "Require tag and its value".

My suggestions is to make Exercise 1, Task 2, Step 4 simpler. The step should just state to change the effect setting from "deny" to "audit".   The rest of the code is the same from the definition that was copied. Very confusing and error prone to overwrite the entire code.

Thanks folks for fixing all the past errors found from last week. You folks rock!

Cheers,
Jeff Smalley MCT
Chicagoville

**Comment by polichtm** [comment]
Hi Jeff,
the first issue is fixed.
The second suggestion is worth considering - it would be helpful to see what others are thinking about this change
rgds
Marcin

**Comment by polichtm** [comment]
updated
rgds
Marcin
