### ISSUE TITLE
Module 02 - Azure Virtual Machines lab tutorial needs updating

### ISSUE THREAD

**Issue by SAIMMINHAS** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#263]
[Module 02 - Azure Virtual Machines
Lab: Deploy and Manage Virtual Machines

Exercise 3: Deploy and configure Azure VM scale sets
Task 3: Install IIS on a scale set VM by using DSC extensions

The 'Extensions' blade for the Virtual Machine Scale Set has now changed in Azure. 

In Task 3, the tutorial asks to browse to the az-100 03_install_iis_vmss.zip file but it's now done in a slightly different way. Hope i'm not doing it wrong.

1. Configuration Modules or Script:
   Browse to Labfiles\Module_02\Deploy_and_Manage_Virtual_Machines\az-100 03_install_iis_vmss.zip and click Open
   Now we've to create a new Storage Account and create a Container in it. Then the az-100-03_install_iis_vmss.zip file needs to be uploaded onto it and then browsed.

Below is what it look like at the current step:
![image](https://user-images.githubusercontent.com/30388154/83648816-6a07a580-a5ae-11ea-8956-7af6f6f751f5.png)

2. The tutorial then says to leave blank the 'Configuration Data PSD1 File:' field. But the current view says that it must be given a value as visible in the above image so not sure what to do. So i just gave it the path
   for az-100-03_install_iis_vmss.zip

Once the 'OK' button is clicked, Azure then installs the extension successfully.

Then, at the 4th step of Task 3, the tutorial says:
     'Navigate to the az1000303vmss0 - Instances blade, select the checkbox for az1000303vmss0_0, 
      and then click on Upgrade to initiate the upgrade. Click Yes.'
![image](https://user-images.githubusercontent.com/30388154/83648975-98858080-a5ae-11ea-8fab-7dfe80c31ebb.png)

However, this process never completes as Azure returns an error message as shown below:
![image](https://user-images.githubusercontent.com/30388154/83649025-a63b0600-a5ae-11ea-9f6b-5ee6ca4c17a5.png)

Please note that all of previous steps of this tutorial are executed successfully but i'm only stuck on this one.

Many thanks.

**Comment by Kangabroo** [comment]
the provisions error is still a problem. I get the same error as above

**Comment by staleycyn** [comment]
This is a reminder that we are not maintaining this repository.

**Comment by spdraptor** [comment]
please end this thing

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
