### ISSUE TITLE
Module 11B - az10001b - Tagging initiative assignment is empty

### ISSUE THREAD

**Issue by darianhuotari** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#265]
When checking the compliance status of "az10001b - Tagging initiative assignment" as outlined in Task 2, Step 9, I see that the compliance state is marked as Compliant, even though there are items in the resource group az1000101b-RG that don't have tags, I see the same thing after creating resource group az1000102b-RG in Task 4, Step 14. When drilling into the az10001b - Tagging initiative assignment - initiative compliance section, it shows 0 non-compliant resources, and 0 total resources. 

This holds true even if I remove existing environment tags from resources in the resource group, like az1000101b-vm1. It's almost like the audit never actually sees anything inside the resource group and the policy shows "Resource Compliance: 100% (0 out of 0)."

![image](https://user-images.githubusercontent.com/66524965/84579127-4992d480-ad80-11ea-89ed-1008c65eb982.png)

I've confirmed the policy is applied to the 1-month free subscription that I'm using, and manually verified that tags are created on some resources (but not others, which is intended) after creating the resource groups via az-100-01b_azuredeploy.json and az-100-01b_azuredeploy.parameters.json. I've also waited a few hours after creating the policy and nothing changes.

Is there something I'm missing with this?

**Comment by darianhuotari** [comment]
Alright - I guess Azure needs a decent amount of time to audit and display the correct remediation status. In my case it was about 10 hours. I checked in on it this morning and it's correctly showing non-compliant items. Hope this helps someone in the future - I'll close this out.

**Comment by spdraptor** [comment]
hey my laptop had battery issue so I gave it to servicing so I didn't received your notification sorry for this thing can I restart this whole course
