### ISSUE TITLE
Deploy Custom Template

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#28]
For some reason the Azure Portal is behaving differently this today when going thru the steps in the labs to deploy a Custom Template.  After clicking the Create button I use to get the attached screen 

![Custom Template Deployment](https://user-images.githubusercontent.com/16696370/58987298-39c7d400-87ad-11e9-944d-0331f247bded.PNG)
 
Now I don't. This will cause a lot of the labs steps not match the template deployment steps. Any ideas????

Cheers,
Jeff Smalley

**Comment by polichtm** [comment]
Hi Jeff,
That’s what I’m still seeing when creating a new template deployment.
What is that you are seeing? Would you mind posting a screenshot?
Rgds
Marcin

**Comment by JeffSmalley** [comment]
![Custom Template Deployment 2](https://user-images.githubusercontent.com/16696370/59000183-5973f200-87d7-11e9-9bbe-5d2034dd0dff.PNG)
It goes to the following screen shot.  Strange it still works for you..

**Comment by polichtm** [comment]
Hi Jeff,
Here is what I’m seeing:

[cid:image001.png@01D51BE6.72A08C50]

How exactly are you getting to that blade?

Rgds
Marcin

**Comment by JeffSmalley** [comment]
4 steps
1. Click Create a Resource
2. Type in Template Deployment
3. Click Create
4. Wrong Screen


![Custom Template Deployment 3](https://user-images.githubusercontent.com/16696370/59003458-081e2f80-87e4-11e9-99fd-cc52ea506213.png)

**Comment by polichtm** [comment]
Hi Jeff,
These are exactly the same steps I’m going through – and the outcome is the same as I posted earlier (different than yours).
Rgds
Marcin

**Comment by JeffSmalley** [comment]
I prepped this course all last week and am teaching it this week and it was working per the lab steps. Today for some reason the website sequence changed for me and my students. Not so much a problem with loaded the template and parameter json files but does change things when a couple labs has us search GitHub for a template. …

**Comment by polichtm** [comment]
Hi Jeff,
That’s the nature of the Azure portal – it does change relatively frequently in sometimes unexpected ways.
This happens to be the primary reason that the lab instructions need to be written in a way that is on one hand sufficiently clear and, on the other, accounts for potential changes to interface elements.
Good luck with the class…
Rgds
Marcin

**Comment by polichtm** [comment]
Ultimately this does not really change much. You simply need to click Edit template - and this will bring you to the very same place you would get to previously.  
In any case, I updated instructions accordingly
rgds
Marcin
