### ISSUE TITLE
Module 12, Exercise 2, Task 6, Step 5 Error

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#29]
This task runs the PowerShell script that maps the "Z" drive. In order to have access to the drive outside the PowerShell session the New-PSDrive command needs to add the "-Persist" switch at the end of the statement before executing. With Step you open File Explorer to connect to the Z drive, With the -Persist switch this can't be done.

Cheers,
Jeff Smalley MCT
Village of Chicago

**Comment by polichtm** [comment]
updated
rgds
Marcin
