### ISSUE TITLE
Module 12, Exercise 2, Task 1 issue

### ISSUE THREAD

**Issue by GerardoAttardi** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#31]
File Sync agent is no longer V5 (StorageSyncAgent_V5_WS2016.msi.)

Now it is: StorageSyncAgent_V6_WS2016.msi

Best

**Comment by polichtm** [comment]
Hi Gerardo,
I'm not sure what you mean. 
here is the current content of that task:
"Within the RDP session, start another instance of Internet Explorer, browse to Microsoft Download Center at https://go.microsoft.com/fwlink/?linkid=858257 and download the Azure File Sync Agent Windows Installer file StorageSyncAgent_V6_WS2016.msi."
pls advise
rgds
Marcin
