### ISSUE TITLE
Module 9 Lab

### ISSUE THREAD

**Issue by jmenne** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#34]
In Lab 09: Implement Directory Syncronization the azure-quickstart-template "active-directory-new-domain" seems to be broken!

It worked for me to change the _artifacts Location value from "[deployment().properties.templateLink.uri]" to 
"https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/active-directory-new-domain/"

Wouldn't it be better not to use changeable public templates?
Is there a way to put a working, not changeable template into the labfiles folder to avoid issues?

**Comment by polichtm** [comment]
Can you advise what specifically was the error message was?
In general, you should not have to modify this parameter.
Regarding changes to this particular template, it would be actually simpler to create a fork and reference it in the lab. We'll look into the proper approach once this issue is resolved
rgds
Marcin

**Comment by jmenne** [comment]
This is the error message:

{
  "telemetryId": "95ba5037-5f9f-441c-8d0e-aae72e1185bb",
  "bladeInstanceId": "Blade_ac3443bbaed34caca5e15d3006ee858e_88_0",
  "galleryItemId": "Microsoft.Template",
  "createBlade": "DeployToAzure",
  "code": "InvalidTemplate",
  "message": "Bereitstellungsvorlagenvalidierung ist fehlgeschlagen: \"Die Vorlagenressource \"_artifactsLocation\" ist in Zeile \"59\" und Spalte \"31\" ungültig: Die Sprachausdruckseigenschaft \"templateLink\" ist nicht vorhanden, verfügbare Eigenschaften sind \"template, templateHash, parameters, mode, debugSetting, provisioningState\".. Details zur Syntax finden Sie unter https://aka.ms/arm-template-expressions.\"."
}

**Comment by polichtm** [comment]
My German is a bit rusty... ;) 
Just to make sure, this is the error you are seeing without modifying the parameter - correct?
rgds
Marcin

**Comment by jmenne** [comment]
yes.
The messages says, that templateLink is not a valid expression

**Comment by jmenne** [comment]
Hi Marcin,
I've tried it with powershell
```powershell
$resourceGroupName = "az10005-RG"
$location = "westeurope"

New-AzResourceGroup -Name $resourceGroupName -Location $location
New-AzResourceGroupDeployment -ResourceGroupName $resourceGroupName `
  -TemplateUri "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/active-directory-new-domain/azuredeploy.json" `
  -TemplateParameterFile 'P:\Microsoft Courseware\Azure-AZ\AZ-103T00A-Mai\lab9parametersFile.json'
```

The error message is:
New-AzResourceGroupDeployment : 11:06:06 - Resource Microsoft.Resources/deployments 'VNet' failed with message '{
  "error": {
    "code": "InvalidTemplate",
    "message": "Unable to process template language expressions for resource 
'/subscriptions/b424000b-b098-435d-b67c-e9fd4c13e0da/resourceGroups/az10005-RG/providers/Microsoft.Resources/deployments/VNet' at line '99' and column 
'9'. 'The template language function 'uri' expects its first argument to be a uri string. The provided value is 
'[deployment().properties.templateLink.uri]'. Please see https://aka.ms/arm-template-expressions/#uri for usage details.'"
  }
}'

The lab9parametersFile.json used looks like this:
```json
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "adminUsername": {
      "value": "Student"
    },
    "adminPassword": {
      "value": "Pa55w.rd1234"
    },
    "domainName": {
      "value": "adatum.com"
    },
    "dnsPrefix": {
      "value": "adatumjm"
    },
    "vmSize": {
      "value": "Standard_D2s_v3"
    },
    "_artifactsLocation": {
      "value": "[deployment().properties.templateLink.uri]"
    }
  }
}
```

rgds
Jörg

**Comment by jmenne** [comment]
Hi again,
here is the error message from the portal in english:
```json
{
  "telemetryId": "8bb4af23-5fe6-493f-9baa-add00f053778",
  "bladeInstanceId": "Blade_09c810d14d4b4d63b3456363ecc86254_7_0",
  "galleryItemId": "Microsoft.Template",
  "createBlade": "DeployToAzure",
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: 'The template resource '_artifactsLocation' at line '59' and column '31' is not valid: The language expression property 'templateLink' doesn't exist, available properties are 'template, templateHash, parameters, mode, debugSetting, provisioningState'.. Please see https://aka.ms/arm-template-expressions for usage details.'."
}
```

**Comment by polichtm** [comment]
You should be able to deploy the template directly from GitHub. I updated the instructions accordingly. Pls give it a try
rgds
Marcin

**Comment by jmenne** [comment]
Hi Marcin,
it worked as you described it! Thank you so much.

rgds
Jörg

**Comment by polichtm** [comment]
You're welcome
rgds
Marcin
