### ISSUE TITLE
Lab files needed

### ISSUE THREAD

**Issue by steveluper** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#37]
The document indicates "Lab files: none" but steps 6 and 9 refer to  az-101-04b_azuredeploy.json and az-101-04b_azuredeploy.parameters.json.

Please indicate that these are needed for the lab.

**Comment by polichtm** [comment]
hi Steve,
pls indicate which lab you are referring to
rgds
Marcin

**Comment by steveluper** [comment]
Azure AD Identity Protection

**Comment by polichtm** [comment]
updated
