### ISSUE TITLE
Labfiles\AZ-100.3\az-100-03_deploy_azure_vm.ps1 does not exist

### ISSUE THREAD

**Issue by jaywilliams916** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#40]
Lab instructions 02a say that Labfiles\AZ-100.3\az-100-03_deploy_azure_vm.ps1 is part of the lab files but it isn't in there. I don't see it referenced again in the rest of the instructions though.

**Comment by polichtm** [comment]
updated
