### ISSUE TITLE
Module 05 No Longer BGP Route Propagation (Instruction/LAK)

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#44]
Hello:
In Lab: VNet Peering and Service Chaining (Module 05) | Exercise 2: Implement custom routing | Task 2: Configure user defined routing | Step 4, it is no longer BGP route propagation but is now called "Virtual Network Gateway Route Propagation".   

![image](https://user-images.githubusercontent.com/41710326/59296339-58b1e480-8c4b-11e9-8063-64e429c9bae8.png)

![image](https://user-images.githubusercontent.com/41710326/59296473-b1817d00-8c4b-11e9-8ccc-3d611d9c1923.png)

**Comment by polichtm** [comment]
updated
