### ISSUE TITLE
Incorrect quote character

### ISSUE THREAD

**Issue by steveluper** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#47]
Self-Service Password Reset lab. Ex 1, Task 5, Step 3

At -- Advanced rule: (user.department -eq “Sales”) -or (user.department -eq “Finance”)

Quotes seem to be special characters rather than a regular double quote " so don't work if pasted into the Azure portal.

**Comment by polichtm** [comment]
Hi Steve,
are you actually copying them from the GitHub page?
rgds
Marcin

**Comment by steveluper** [comment]
Correct. Students are either copying and pasting from the GitHub page or retyping and one discovered the special character in doing so.

**Comment by polichtm** [comment]
This works perfectly fine for me. You obviously can verify what is available directly on GitHub. 
Have you tried it yourself?
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
