### ISSUE TITLE
Module 6 Lab - Wrong Server Name Listed

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#48]
Module 6 Lab
Exercise 2, Task 1, Step 3
In the note, the VM Name is wrong. It should be az1010302b-vm1

Incorrect Version
"Note: 10.203.16.4 is the private IP address of the second Azure VM az1010301b-vm1 which you deployed to another Azure region."

Corrected Version
"Note: 10.203.16.4 is the private IP address of the second Azure VM az1010302b-vm1 which you deployed to another Azure region."

Thanks for your awesome speed in getting all the bugs fixed. Much appreciated!

Jeff Smalley MCT
Village of Chicago

**Comment by polichtm** [comment]
Hi Jeff,
which lab are you referring to (title)?
rgds
Marcin

**Comment by JeffSmalley** [comment]
o	Module 6 ---Azure Network Watcher (az-101-03b)

**Comment by polichtm** [comment]
updated
