### ISSUE TITLE
Suggested change to lab 10

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#54]
Moduel 10 lab, Exercise 2 Task 2 pt.4: you need to add 
"Within the RDP session to az1010401b-vm1, from Server Manager, disable temporarily IE Enhanced Security Configuration."
Otherwise you won't be able to do anything in IE

**Comment by polichtm** [comment]
Which lab are you referring to?
rgds
Marcin

**Comment by tbkobberoe** [comment]
Sorry, it is Module 10 lab, Exercise 2 Task **4** pt.4. The "Lab: Azure AD Identity Protection" lab

**Comment by polichtm** [comment]
completed
