### ISSUE TITLE
11b - Governance and Compliance (az-100-01b).md - Correction

### ISSUE THREAD

**Issue by JS-Jake** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#55]
10 - Azure AD Identity Protection (az-101-04b).md 
Excersize 1, Task 5, Point 3
"Add the built-in policy definition named Apply tag and its default value" should now be
"Add the built-in policy definition named **Append** tag and its default value "

**Comment by polichtm** [comment]
I assume you meant 11b - not 10. 
updated...

**Comment by JS-Jake** [comment]
Lovely, thanks :)
