### ISSUE TITLE
Lab 12 Implement Azure File Sync error in ps command

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#56]
In Exercise 1 task 3 pt. 3 the command 
"Install-Module -Name Az.StorageSync -AllowPrerelease -AllowClobber -Force" should be changed to 
"Install-Module -Name Az.StorageSync -AllowClobber -Force" 
as the -Allowprerelease ins't available/necessary anymore

**Comment by polichtm** [comment]
updated
rgds
Marcin
