### ISSUE TITLE
Lab 12 Implement Azure File Sync suggestion for improvement of step

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#57]
In Exercise 2 task 6 pt. 2 it states:
"In the Azure portal, navigate to the az10002bshare1 blade and display the Connect blade"
As the students at this point is in the az1000202b-syncgroup1 blade they'll probably just click on the cloud endpoint az10002bshare1, and from here they'll not be able to connect. Could the text be changed to something like
"In the Azure portal, navigate to the blade for the storage account you created earlier in the lab, go to "Files" tab and then click on the az10002bshare1 file share.
On the az10002bshare1 blade, click on the Connect button.

**Comment by polichtm** [comment]
updated
rgds
Marcin
