### ISSUE TITLE
Section of Module 2 Exercise 2 error

### ISSUE THREAD

**Issue by jasonpnnl** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#63]
In file: AZ-103-MicrosoftAzureAdministrator/Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md

In task 3 there is a section that says:

> In the Cloud Shell pane, run the following command, substituting the placeholder <custom-label> with any string which is likely to be unique and the placeholder <location-of-az1000301-RG> with the name of the Azure region in which you created the az1000301-RG resource group.

However the code snippet has been updated to automatically pull the RG location using $rg.location. 

> Test-AzDnsAvailability -DomainNameLabel <custom-label> -Location $rg.Location

Quick fix to make the words match the code snippet.

**Comment by polichtm** [comment]
Hi Jason,
could you clarify which exercise and task you are referring to?
thnx
Marcin

**Comment by polichtm** [comment]
completed

**Comment by jasonpnnl** [comment]
https://github.com/MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator/blob/master/Instructions/Labs/02a%20-%20Deploy%20and%20Manage%20Virtual%20Machines%20(az-100-03).md

Line 399.

**Comment by jasonpnnl** [comment]
Glad you found it, thanks for fixing it.

**Comment by polichtm** [comment]
certainly - you're welcome
