### ISSUE TITLE
Typo in Lab: Implement and Manage Storage

### ISSUE THREAD

**Issue by jasonpnnl** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#64]
In https://github.com/MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator/blob/master/Instructions/Labs/03%20-%20Implement%20and%20Manage%20Storage%20(az-100-02).md

> From the Blobs blade of the second storage account, navigate to the container az1000202-container, and then open the az-100-02_azuredeploy.json blade.

Should be:

>  From the Blobs blade of the second storage account, navigate to the container az1000203-container, and then open the az-100-02_azuredeploy.json blade.

**Comment by polichtm** [comment]
updated
