### ISSUE TITLE
query for resource name is broken

### ISSUE THREAD

**Issue by junhe231** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#65]
All labs end with querying resource group by JMESPATH "[?starts_with(name,'az1000')]".name.  It failed in my Cloud shell.  I fixed by shifting quote to the end of name, "[?starts_with(name,'az1000')].name" .  Please fix them so It will not frustrate others. 

PS Azure:\> az group list --query "[?starts_with(name,'az10101')]".name --output tsv
az group list: error: argument --query: expected one argument
usage: az group list [-h] [--verbose] [--debug]
                     [--output {json,jsonc,table,tsv,yaml,none}]
                     [--query JMESPATH] [--tag [TAG]]
                     [--subscription _SUBSCRIPTION]
Azure:/
PS Azure:\> az group list --query "[?starts_with(name,'az10101')].name" --output tsv
az1010101-RG
az1010101-RG-asr

**Comment by polichtm** [comment]
You are supposed to run this from Bash shell - not PowerShell shell...
rgds
Marcin

**Comment by junhe231** [comment]
If you make the change I suggested, it will be able to run in both.

**Comment by polichtm** [comment]
Completed…
