### ISSUE TITLE
Lab: Azure AD Identity Protection MFA moved

### ISSUE THREAD

**Issue by EdGale-MFST** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#68]
The MFA blade has moved under the Security blade in Azure AD overview. See task 5, Step 2 and step 9.

**Comment by polichtm** [comment]
Not as far as I can tell. Are you having issues accessing the multi-factor authentication portal as per instructions?
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
