### ISSUE TITLE
Labs are not Free Trial Friendly

### ISSUE THREAD

**Issue by iBattosai** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#69]
There are many exercises that require you to create multiple VMs. Which you are unable to do due to core limitations with the Free Trial. In order to work around this you have to switch to pay as you go. 

VNet Peering and Service Chaining

Exercise 0: Prepare the Azure environment

Task 2: Create the second virtual network in the same region hosting a single Azure VM by using an Azure Resource Manager template

**Comment by polichtm** [comment]
You don't have to. You have two other options:
- use smaller VM sizes (which was the primary reason that https://github.com/MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator/issues/53 was raised)
- bump up the number of quotas (https://docs.microsoft.com/en-us/azure/azure-supportability/resource-manager-core-quotas-request)
rgds
Marcin

**Comment by mreherefortea** [comment]
Hello,
Thank you for advising but I don't believe a free trial user can request a bump in the quota limits.

**Comment by tiagocostapt** [comment]
@mreherefortea Azure Pass Subscription can. This is the type of subscription you should get when taking this class. Nevertheless my students last week took all the labs without any big issues. You need to delete all the resources when finish a lab.

**Comment by polichtm** [comment]
@mreherefortea  - you are correct - Free trial does not allow for quota limits and, from what I recall, it is limited to 4 cores per region (pls confirm whether the latter is correct).
Do you see a significant percentage of students using Azure free trial? 
rgds
Marcin

**Comment by mreherefortea** [comment]
Thank you for clarifying and advising Tiago. Thank you following up Marcin, I have not seen many reports from students running into this issue yet (just a single student). Thank you both for your time.

**Comment by polichtm** [comment]
you're welcome
rgds
Marcin
