### ISSUE TITLE
Blob to blob sync not working

### ISSUE THREAD

**Issue by shkumesh** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#70]
I tried to use following command, But it did not work:

`azcopy --source https://$storageAccount1Name.blob.core.windows.net/az1000202-container/ --destination https://$storageAccount2Name.blob.core.windows.net/az1000203-container/ --source-key $storageAccount1Key1 --dest-key $storageAccount2Key1 --include "az" --sync-copy --recursive`

Below is the error :

```
Error: unknown flag: --source
  azcopy [command]
```

So I modified command like bellow:

`azcopy sync "https://$storageAccount2Name.blob.core.windows.net/az1000202-container/" "https://$storageAccount1Name.blob.core.windows.net/az1000203-container/"--recursive`

But no luck and getting following error:

```
error parsing the input given by the user. Failed with error source 'https://az1000202rgsg.blob.core.windows.net/az1000202-container/' / destination 'https://az1000201rgsg1.blob.core.windows.net/az1000203-container/' combination 'BlobBlob' not supported for sync command
Azure:/
```

**Comment by polichtm** [comment]
Pls clarify which lab, exercise, and task/step you are referring to
rgds
Marcin

**Comment by GerardoAttardi** [comment]
Hi, the syntax you are using works in AZCopy 8.1

If you just downloaded and installed AZCopy, probably you are using AZCopy 10.x

Syntax has changed significantly...... SOURCE parameter is not longer used, ACCESS KEYS are not longer used for authentication.... you need to use SAS (Shared Access Signatures)

An example below:
azcopy cp "C:\myfolder\*" "https://YOURSTORAGEACCOUNT.blob.core.windows.net/FOLDER/?sv=YOURSAS" --recursive=true  

Will look like this: 
azcopy cp "C:\myfolder\*" "https://YOURSTORAGEACCOUNT.blob.core.windows.net/photos/?sv=2018-03-28&ss=bfqt&srt=sco&sp=rwdlacup&se=2019-06-07T13:30:00Z&st=2019-06-07T04:30:00Z&spr=https,http&sig=u5bUaEKOXJHqSbWVK16SiOgcI2SVg8mLAr2ujKWe%2F%2FI%3D" --recursive=true

To take a look about AZCopy 10 syntax, please refer to:
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10

Best,
Gerardo

**Comment by shkumesh** [comment]
Hi Marcin/Gerardo,

I'm referring : Lab: Implement and Manage Storage (Task 4: Copy a container and blobs between Azure Storage accounts).

I tried this using Cloud Shell pane, What is the correct syntax for Cloud Shell pane?

```
PS Azure:\> az --version
azure-cli                         2.0.69

command-modules-nspkg               2.0.3
core                              2.0.69
nspkg                              3.0.4
telemetry                          1.0.3

Python location '/opt/az/bin/python3'
Extensions directory '/home/kalum/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Jul 11 2019, 08:40:03)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
Azure:/
```

**Comment by polichtm** [comment]
Pls use the Bash session (not PowerShell session), as instructed
Rgds
Marcin

**Comment by polichtm** [comment]
updated
rgds
Marcin
