### ISSUE TITLE
Can not select region

### ISSUE THREAD

**Issue by shkumesh** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#72]
Lab: Load Balancer and Traffic Manager
Task 2: Implement Azure Traffic Manager load balancing

```
4. From the Create Traffic Manager profile blade, create a new Azure Traffic Manager profile with the following settings:
Location: either of the Azure regions you used earlier in this lab
```

But I can not select location(It is disabled)
![image](https://user-images.githubusercontent.com/48082518/61526909-f6fa4c80-aa38-11e9-9d59-71f317181aec.png)

Once I created the Azure Traffic Manager, it shows location as global.
![image](https://user-images.githubusercontent.com/48082518/61527288-b3eca900-aa39-11e9-80ee-e0e3ab7beec9.png)

I can not select the public ip address for end points.

![image](https://user-images.githubusercontent.com/48082518/61527368-e8f8fb80-aa39-11e9-83d5-56cf848ab447.png)

**Comment by polichtm** [comment]
Updated.
Regarding the public IP addresses - have you assigned the DNS names as instructed?
rgds
Marcin
