### ISSUE TITLE
Proposed change / fix to the "Creating Virtual Machines" Demo

### ISSUE THREAD

**Issue by caioribeirocesar** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#73]
Here is some feedback about Skillpipe lab issues we faced during the SSP delivery and what can be done to improve user experience.

A) Module 2 "Azure Virtual Machines":

Creating Virtual Machines / Demonstration - Creating a VM in the portal

> This information needs to be moved to the end of PowerShell (Example 2), since we are actually using the ResourceGroup "myResourceGroup" in the PowerShell exercise.

 Clean up resources
✔️ When no longer needed, you can delete the resource group, virtual machine, and all related resources.

To do so, select the resource group for the virtual machine, select Delete, then confirm the name of the resource group to delete.

>

B) Module 2 "Azure Virtual Machines":

Creating Virtual Machines / PowerShell - Example (Part2)

The variable "$nic" was not set before. Meaning students fail in the exercise below with the error:

"" 

> _Add-AzVMNetworkInterface : Cannot validate argument on parameter 'Id'. The argument is null or empty. Provide
> an argument that is not null or empty, and then try the command again._

""

The new NIC needs to be connected to a subnet, thus we need to have the specific subnet ID. For that, we also need a vnet.

Also, the ResourceGroup mentioned in the bullet 7 is "myResourceGroupVM" and not "myResourceGroup", meaning the lab fails with:

_

> Resource group 'myResourceGroupVM' could not be found.

_

(this is also why we need to move the information text mentioned above to this section)

This can fix the demo, **but my feedback is to change the approach of the lab:**

6. Create a network interface card to be added to the virtual machine configuration with New-AzNetworkInterface:

```
$myVNet = New-AzVirtualNetwork -ResourceGroupName myResourceGroup -Location EastUS -Name myVNet -AddressPrefix 10.0.0.0/16 
Add-AzVirtualNetworkSubnetConfig -Name mySubnet -AddressPrefix 10.0.0.0/24 -VirtualNetwork $myVNet
$netID = (Get-AzVirtualNetworkSubnetConfig -VirtualNetwork $myvnet).id 
$IPconfig = New-AzNetworkInterfaceIpConfig -Name "IPConfig1" -PrivateIpAddressVersion IPv4 -PrivateIpAddress "10.0.1.10" -SubnetId $netID
New-AzNetworkInterface -Name "NetworkInterface1" -ResourceGroupName "myResourceGroup" -Location "EastUs" -IpConfiguration $IPconfig

```

7. Add the network interface card to the virtual machine configuration with Add-AzureRmVMNetworkInterface:

`
$vm = Add-AzVMNetworkInterface -VM $vm -Id NetworkInterface1
`

7. Create the virtual machine with New-AzVM: 

`
New-AzVM -ResourceGroupName myResourceGroup -Location EastUS -VM $vm
`

 MY FEEDBACK ABOUT THIS LAB AND WHAT NEEDS TO BE DONE 

In this section, we have not yet discussed about Vnets, Subnets and NICs. Meaning students will go trough this in the creation before actually having that discussion.

Instead, we can ask in this exercise for them to run the cmdlet below; it's from Azure Quickstart (https://docs.microsoft.com/en-us/azure/virtual-machines/windows/quick-create-powershell).

I believe this to be a better approach in terms of technical depth to understand the pshell cmdlets above and also to prevent the VNET and Subnet discussion before the topics arrive.

It would look like this:

PowerShell - Example

You can also create a virtual machine using PowerShell.

In this example, a virtual machine is created with a name of myVM running the latest version of Windows Server 2016 Datacenter.

```

New-AzVm `
    -ResourceGroupName "myResourceGroup" `
    -Name "myVM" `
    -Location "East US" `
    -VirtualNetworkName "myVnet" `
    -SubnetName "mySubnet" `
    -SecurityGroupName "myNetworkSecurityGroup" `
    -PublicIpAddressName "myPublicIpAddress" `
    -OpenPorts 80,3389

```

**Comment by polichtm** [comment]
Just to clarify - you are referring to demos - not labs - correct?
rgds
Marcin

**Comment by caioribeirocesar** [comment]
Yes, the demo named “Powershell 2”.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by staleycyn** [comment]
Since this is Demo related and not Lab related, I will take care of this separately.
