### ISSUE TITLE
Can not delete AD

### ISSUE THREAD

**Issue by shkumesh** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#74]
Lab: Implement Directory Synchronization
Task 2: Delete resource groups

Note: To remove the Azure AD tenant you created in this lab, follow https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-delete-howto

I can not delete AD and getting below message:

![image](https://user-images.githubusercontent.com/48082518/61612441-3795d800-ac7c-11e9-8eee-78616e3d4d70.png)

**Comment by polichtm** [comment]
As the required actions suggest:
- make sure that you deleted all user objects (except for the account that you are using to delete the tenant)
- make sure that the account is a Global Administrator
rgds
Marcin

**Comment by shkumesh** [comment]
I can not delete users, because delete button is disabled.

![image](https://user-images.githubusercontent.com/48082518/61762984-5bc6f580-adf1-11e9-9628-0c92c51e8dcc.png)

![image](https://user-images.githubusercontent.com/48082518/61763009-6d100200-adf1-11e9-89ff-58249dc2725a.png)

**Comment by polichtm** [comment]
You will not be able to delete all accounts (you need to delete all except for one).

In addition, it appears that you still have directory synchronization turned on. 

As per https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-delete-howto referenced above:

There can be no users in the directory except one global administrator who is to delete the directory. Any other users must be deleted before the directory can be deleted. If users are synchronized from on-premises, then sync must first be turned off, and the users must be deleted in the cloud directory using the Azure portal or Azure PowerShell cmdlets.

rgds
Marcin

**Comment by Franlusan** [comment]
I Will try to follow you instructions. Thank you

**Comment by polichtm** [comment]
Did you manage to complete this successfully?
rgds
Marcin

**Comment by Franlusan** [comment]
No. I am waiting for your remote connection but after 2 WEEKS the situación has not changed. Pf!!!

Francisco Luque
Microsoft & ITIL Trainer

________________________________

**Comment by polichtm** [comment]
What do you mean by "remote connection"?
rgds
Marcin

**Comment by tralalas** [comment]
Hello so I have the same issue as polichtm :)
I believe that before removing the resource group with the ad vm I should have stopped the sync between the tenant and the ad on the vm.
From what I can see the only users that I can't delete are the users that have as source windows server AD the other 2 I can remove 
Any suggestions ? probably there is something that can be done from the azure cloud shell ?
Thank you

![az_1](https://user-images.githubusercontent.com/53567122/62293420-dc789800-b468-11e9-93f1-a695ac9bb8fe.PNG)
![az_2](https://user-images.githubusercontent.com/53567122/62293425-e00c1f00-b468-11e9-8889-6fb59fa0e4e2.PNG)
![az_3](https://user-images.githubusercontent.com/53567122/62293429-e3070f80-b468-11e9-8d8a-7b80fc326824.PNG)

**Comment by polichtm** [comment]
You should be able to disable Azure AD Connect from the Azure AD Connect blade in the Azure portal (accessible via the Azure AD tenant blade)
rgds
Marcin

**Comment by tralalas** [comment]
Hi Marcin,

Sorry I really don't see it how 

![image](https://user-images.githubusercontent.com/53567122/62299891-21ef9200-b476-11e9-9324-2ff193f1d0e9.png)

Thank you,
Sorin

**Comment by polichtm** [comment]
Try the following:

From the Windows PowerShell console on the lab VM, install the MsOnline PowerShell module by running the following (when prompted, in the NuGet provider is required to continue dialog box, click Yes):
Install-Module MsOnline -Force

From the Windows PowerShell console on the lab VM, connect to the AdatumSync Azure AD tenant by running the following (when prompted, sign in with the SyncAdmin credentials):
Connect-MsolService

From the Windows PowerShell console on the lab VM, disable the Azure AD Connect synchronization by running the following:
Set-MsolDirSyncEnabled -EnableDirSync $false -Force

From the Windows PowerShell console on the lab VM, verify that the operation was successful by running the following:
(Get-MSOLCompanyInformation).DirectorySynchronizationEnabled 

rgds
Marcin

**Comment by polichtm** [comment]
Did you manage to complete this successfully?
rgds
Marcin

**Comment by polichtm** [comment]
I updated the lab instructions - pls follow them and let me know if you run into any issues
rgds
Marcin

**Comment by tralalas** [comment]
Hi Marcin,
THank you now I was able to get rid of all the users and left only my global user, but now I have another issue and is pretty strange because yesterday I wasn't able to remove the tenant because of users while all the other checks or validated , now all of the checks are validated except the enterprise applications :)

![image](https://user-images.githubusercontent.com/53567122/62351495-f87e4700-b505-11e9-9117-ba004ff46d89.png)

**Comment by polichtm** [comment]
Pls follow https://blogs.msdn.microsoft.com/kennethteo/2017/09/19/deleting-azure-ad-tenant/
rgds
Marcin

**Comment by polichtm** [comment]
@tralalas 
Pls advise where this stands
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
