### ISSUE TITLE
az-100-03_azuredeploy.json incorrect VNET name

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#75]
HI,

Lab 02a - Deploy and Manage Virtual Machines (az-100-03)

Ex 1 Task 1 creates az1000301-vm0 and creates VNET az1000301-RG-vnet
Ex 1 Task 2 creates az1000301-vm1 and attaches to VNET az1000301-RG-vnet
Ex 1 Task 3 creates az1000302-vm's and attempts to attach to VNET az1000301-vnet0

Could az-100-03_azuredeploy.json please be amended to use the correct VNET name of az1000301-RG-vnet? (As the deployment currently fails due to the wrong name)

Thanks in advance

**Comment by tiagocostapt** [comment]
I just tried and it finished deploying correctly.

**Comment by djcmct** [comment]
I understand that the instructions in the lab instructions are correct and that it can be changed in the template deployment interface, but, when we're trying to promote the use of templates as a way of achieving consistent deployments without having to know or amend parameters, then having to do so defeats the purpose.

My request was to amend the json with the correct value ;)

**Comment by polichtm** [comment]
The use of templates does not imply that the person performing the deployment does not need to be concerned about their parameters. IMHO, it's actually the opposite - the primary focus in such scenario should be ensuring that the parameters are correct. Parameters can be assigned in several different ways - I believe there is a benefit in having students experiment with at least two of them (via a parameters file and via GUI). 
rgds
Marcin

**Comment by polichtm** [comment]
addressed by PR#77

**Comment by djcmct** [comment]
Thanks for the response, my opinion is a little different.
IMHO templates are useful for many reasons, one of which is to provide "junior" administrators with a mechanism that eliminates human error when performing deployment tasks.
As this course has no pre requisite of Azure admin experience, then i'd suggest that delegates could be classified as "junior".
As such, I personally would only include parameters that were constant and either have different templates to deploy any differences or have a master template and then leave the parameters blank that required changing.
If the intention for this lab is to get delegates to experiment, then perhaps leaving the VNET blank would then require the delegate to check the template against the details in the instructions.
As this is the first lab in the course the delegates haven't yet learned the naming convention used and are failing to spot the different name.

**Comment by tiagocostapt** [comment]
I have to agree with @polichtm , templates are create to provide different values on the parameters. 
@djcmct when you have that scenario we create ARM templates without parameters. 

IMHO this lab might get better if some of the parameters are empty by default and Students need to provide the values. That way maybe we can have a better approach. Just drop this here for discussion and for @polichtm provide is view on the topic.

**Comment by polichtm** [comment]
I believe that Gran'ts PR #77 should eliminate potential confusion.
Pls let me know if you think otherwise
rgds
Marcin

**Comment by djcmct** [comment]
Perfect,

Thank you :)
