### ISSUE TITLE
DEMO "Azure Files/ Demonstration File Shares" adding more information

### ISSUE THREAD

**Issue by caioribeirocesar** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#76]
The demonstration of creating a file share through PowerShell will fail **if the students don't have the understanding that they need to add the correct values** (which happened in the past):

`$storageContext = New-AzStorageContext storage-account-name storage-account-key`

/\ this string won't work as the values need to be added.

This can help them to gather the information thru Pshell:

Create a file share (PowerShell)

1. Gather the storage account name and the storage account key.

```
Get-AzStorageAccount | fl *name*
Get-AzStorageAccount -ResourceGroupName "YourResourceGroupName" -Name "YourStorageAccountName"
```

2. Create a context for your storage account and key. The context encapsulates the storage account name and account key.

`$storageContext = New-AzStorageContext -StorageAccountName "YourStorageAccountName" -StorageAccountKey "YourStorageAccountKeyValue"`

3. Create the file share. The name of your file share must be all lowercase.

`$share = New-AzStorageShare logs -Context $storageContext`

**Comment by staleycyn** [comment]
This GitHub site is for Lab issues only, not Instructor demonstration issues. Apologies if that wasn't clear in a previous post. I will address this in the Teams site.
