### ISSUE TITLE
Lab files are missing

### ISSUE THREAD

**Issue by shkumesh** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#80]
Lab files are missing for below labs

Lab: Migrate on-premises Hyper-V VMs to Azure

```
Lab files:

Allfiles/Labfiles/AZ-101.1/az-101-01b_azuredeploy.json

Allfiles/Labfiles/AZ-101.1/az-101-01b_azuredeploy.parameters.json

Allfiles/Labfiles/AZ-101.1/DSC/InstallHyperV.ps1

Allfiles/Labfiles/AZ-101.1/DSC/InstallHyperV.zip
```

Lab: Secure Identities

```
Lab files:

Labfiles\AZ-101.4\az-101-04_01_azuredeploy.json

Labfiles\AZ-101.4\az-101-04_01_azuredeploy.parameters.json

Labfiles\AZ-101.4\az-101-04_01_customRoleDefinition.json
```

**Comment by djcmct** [comment]
lab files for the optional labs are here

https://github.com/MicrosoftLearning/AZ-101-MicrosoftAzureIntegrationandSecurity

(would be handy if these could be copied into this repo)

**Comment by staleycyn** [comment]
This course, AZ-103, does not include those labs. So, they are not part of this repository.

**Comment by polichtm** [comment]
Removed the lab instructions
rgds
Marcin

**Comment by djcmct** [comment]
the README does suggest that the Privileged Identity Management (az-101-04) lab is still part of this course,
As the lab has now been removed, could this please be updated.

Regards,

**Comment by polichtm** [comment]
valid point - updated
rgds
Marcin
