### ISSUE TITLE
Step missing in creation of RDP file

### ISSUE THREAD

**Issue by CJ1S** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#82]
Lab Instructions: 
Module 4, Task 4, Line 2

"2. From the Overview pane of the az1000402b-vm2 blade, generate an RDP file and use it to connect to az1000402b-vm2."

before they can generate an RDP file, they have to click the connect button to pop a new blade with the information and the link to generate the RDP file. MOST of my students missed this step.

**Comment by polichtm** [comment]
Could you clarify how much experience do these students have with Azure? 
Pls note that AZ-103 was not designed as an introductory course to Azure. Effectively, the labs do not follow the traditional "click-through" approach (using such approach would also considerably increase the maintenance overhead). 
rgds
Marcin

**Comment by CJ1S** [comment]
they have mid level experience. They for the most part can troubleshoot issues on their own, but when learning new building processes such as building the RDP file, the task is virtually a walk-thru then skips this. The task seems to insinuate that they should find a way to generate the file on the Overview pane instead of the Connect pane inside the overview.

**Comment by polichtm** [comment]
So just to make sure that there is clarity regarding this - your students know very well how to connect via RDP to an Azure VM (which "mid level" experience would typically imply) - but they were confused by the wording - correct?

If so, would the following suffice?

"2. Connect to az1000402b-vm2 via RDP."

If not, what would be your suggestion?

rgds
Marcin

**Comment by CJ1S** [comment]
"2. From the Overview pane of the az1000402b-vm2 blade, use **connect** and generate an RDP file to connect to az1000402b-vm2."

I think the wording is off.. but describing that the generation is on a different blade than the overview page is the biggest hurdle here. When they recognize the right blade then they know what they need to do. Its more of "which blade do I need to be on, to find my next piece of the puzzle?"

**Comment by polichtm** [comment]
Would you expect someone with "mid level" experience with Azure to know how to connect to an Azure VM via RDP?
rgds
Marcin

**Comment by CJ1S** [comment]
alot of the AZ admins I have worked with that are az100 and 101 certified have to go look this up, its not a repetitive task they daily. typically they receive a request for VM creation, they identify the IP/Port info and give this to the requestor, not an RDP file.

**Comment by tiagocostapt** [comment]
@CJ1S and @polichtm I teach this and other Azure classes a lot and never had a problem with this specific step. This week I was teaching this and in a full class every one did this without any issues. Almost all of then were new to Azure. Before they did the lab there are demos when the trainer should do a similar step. I think it's clear just saying. Connect! In the exam they will not have any help from anyone, labs need to me a little bit more generic and not so super detailed step by step... Just my 2 cents.

**Comment by polichtm** [comment]
Hi Tiego,
appreciate sharing your opinion
rgds
Marcin

**Comment by CJ1S** [comment]
If others feel this is a mute point, I can work around it with my students. Tiago described to me how he sets up and demo's the lab himself before the students actually do it. This would eliminate this discussion.  I would like to see the change but others feel it may be more trouble than benefit, then leave it. just guessed it to be worthy of reviewing.
