### ISSUE TITLE
Organize labs based on AZ-103? 

### ISSUE THREAD

**Issue by tiagocostapt** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#9]
Should we organize this labs based on the AZ-103 numbering? I think so, that way would be easier for students and MCTs to follow this. 
I'm currently teaching this and I had to do it... 
Waiting the team feedback

**Comment by kramit** [comment]
Have you tried using go deploy labs as your labs online provider for the AZ-103 yet? They have all the labs organised and integrated in to the platform you can contact them for a free MCT account.

http://www.godeploy.it/contact-us/

**Comment by polichtm** [comment]
Hi Tiago,
would you mind posting the numbering you used in this thread?
rgds
Marcin

**Comment by tiagocostapt** [comment]
HI Marcin,

According to the AZ-103T00 Course this is the list of labs: 

Lab02A - Deploy and Manage Virtual Machines | OLD: az-100-03
Lab02B - Virtual Machines and Scale Sets | OLD: az-100-03b
Lab03 -  Implement and Manage Storage | OLD: az-100-02
Lab04 - Configure Azure DNS | OLD: az-100-04b
Lab05 - VNet Peering and Service Chaining | OLD: az-100-04
Lab06 - Network Watcher | OLD: az-101-03b
Lab07 - Azure Site Recovery Between Regions | OLD: az-101-01
Lab08 - Load Balancer and Traffic Manager | OLD: az-101-03
Lab09 - Implement Directory Synchronization | OLD: az-100-05
Lab10A - Azure AD Identity Protection | OLD: az-101-04b
Lab10B - Self-Service Password Reset | OLD: az-100-05b
Lab11A - Role-Based Access Control | OLD: az-100-01
Lab11B - Governance and Compliance | OLD: az-100-01b
Lab12 - File Sync | OLD: az-100-02b

Is this the information you needed? 

Then we need to do the same at the Allfiles fodders.

**Comment by tiagocostapt** [comment]
@kramit Thanks for the feedback. I know GODeploy and I have an account. It's not mandatory to use a Lab hoster to run these courses, so this repo should have it organize has we have with the AZ-103T00-A MOC. Just my 2 cents.

**Comment by polichtm** [comment]
Hi Tiago,
appreciated
rgds
Marcin

**Comment by staleycyn** [comment]
This repository is organized so that instructors for AZ-100, AZ-101, and AZ-103 can find their labs.

**Comment by tiagocostapt** [comment]
Most deliveries starting now will be AZ-103 and not AZ-100/1.
If you want to support AZ-100/1 in this repository I would create the AZ-103 structure and then a document for AZ-100/1 trainers with the matching labs. For me this would make more sense because this is the AZ-103 repo. 
Regards,
Tiago Costa

**Comment by kramit** [comment]
The AZ-100 and AZ-101 have been completely retired in favour of this new AZ-103 as far as I am aware

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tbkobberoe** [comment]
@kramit AZ-100 and AZ-101 WILL retire at the end of June 2019, so @tiagocostapt suggestion still makes sense

**Comment by tiagocostapt** [comment]
@polichtm should we close this issue? Labs are now ordered like we need to teach then in AZ-103.

**Comment by polichtm** [comment]
Hi Tiago,
certainly - closing 
rgds
Marcin
