### ISSUE TITLE
Can not Create NIC via Powershell - Module 02 - Azure Virtual Machines

### ISSUE THREAD

**Issue by LightMoon** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#91]
Hi,

Running the bellow command gives me this error. Where have I done wrong?

`$nic = New-AzNetworkInterface -Name "$($vmName)" -ResourceGroupName $resourceGroup.ResourceGroupName -Location $location -SubnetId $subnetid -PublicIpAddressId $pip.Id -NetworkSecurityGroupId $nsg.Id
New-AzNetworkInterface : Resource /subscriptions/da1177a0-62d0-4993-9bc5-6a7d76b3ce74/resourceGroups/az1000301-RG/providers/Microsoft.Network/virtualNetworks/az1000301-RG-vnet/subnets/subnet0 referenced by resource /subscriptions/da1177a0-62d0-4993-9bc5-6a7d76b3ce74/resourceGroups/az1000301-RG/providers/Microsoft.Network/networkInterfaces/az1000301-vm1 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 'ee0b4a2a-392e-4720-bcd4-fdd51db97415'
At line:1 char:8
+ $nic = New-AzNetworkInterface -Name "$($vmName)" -ResourceGroupName $ ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [New-AzNetworkInterface], NetworkCloudException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureNetworkInterfaceCommand`

**Comment by polichtm** [comment]
Pls clarify which extercise/task/step you are referring to and explain the reason that the first line of the script above has a backtick in front of it
rgds
Marcin

**Comment by LightMoon** [comment]
My bad. I redeployed from starch and it solved the problem.
I have a feeling everything wasn't deployed in the same location (region)
