### ISSUE TITLE
we should specify a name also for the network, not only for the subnet 

### ISSUE THREAD

**Issue by hihoman1980** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#92]
in 02a - Deploy and Manage Virtual Machines (az-100-03) - _"

```
> 1. On the Networking tab, click **Create new** under Virtual Network. Leave the existing default range and subnet, and add the following:
>     - Address range: **10.103.0.0/16**
> 
>     - Subnet name: **subnet0**
> 
>     - Subnet address range: **10.103.0.0/24**"_
```

we should also specify a name for the network, not only for the subnnet. This seems to be to confusing, especially when the network section is lateron.

**Comment by polichtm** [comment]
You don't have to specify it - you accept the default value. Updated for clarity
rgds
Marcin
