### ISSUE TITLE
Cannot deploy two Azure VMs running Linux - Module 02

### ISSUE THREAD

**Issue by LightMoon** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#93]
Hi,

On Task 3 of Module 02 - [Deploy two Azure VMs running Linux into an availability set by using an Azure Resource Manager template](https://microsoftlearning.github.io/AZ-103-MicrosoftAzureAdministrator/Instructions/Labs/02a%20-%20Deploy%20and%20Manage%20Virtual%20Machines%20(az-100-03).html#scenario)

every time I hit the purchase button this error comes up.

 Double checked the Vm Size: is Standard_DS2_v2.

Good to note that I am on Azure for Student Subscription

![6-08-2019 2-53-03 PM](https://user-images.githubusercontent.com/1636991/62512137-1b885e00-b85a-11e9-9285-9a1c5744b7c6.png)

**Comment by polichtm** [comment]
You need to increase the CPU quota limits for your subscription. Follow https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests
rgds
Marcin

**Comment by LightMoon** [comment]
I opened a ticket with support, it turned out my "Azure for Students" subscription do not allow them to increase the limit!
I have to convert to pay as you go.
is there any option to reduce my cost and use any Microsoft Azure for student plans?

**Comment by staleycyn** [comment]
This repository is to support Microsoft Certified Trainers teaching Microsoft Official Courseware. If you are a student enrolled in a course please direct your questions to your instructor. Cindy - Microsoft.
