### ISSUE TITLE
Can not Create NIC via Template - Module 02 - Azure Virtual Machines

### ISSUE THREAD

**Issue by Sudlon** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#97]
Hi, I have almost the same issue as this one: https://github.com/MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator/issues/91

Mine happens at module 2 when deploying using the template. I three double checked whether the regions are the same and whether the resource exist: they are and they do. I also three double checked the virtualNetworkName (az1000301-vnet) and subnetName (subnet0), as well as the virtualNetworkResourceGroup (az1000301-RG). Anything else I missed?

Let me know if anything is unclear

**Comment by Sudlon** [comment]
Wow, reading is difficult... I now see the virtualNetworkName should be "az1000301-RG-vnet" (note the "-RG" in it). Apologies for opening the issue; it took me quite a while to find it.

**Comment by polichtm** [comment]
np - good to see you managed to get this one figured out ;)
rgds
Marcin
